# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class AccessGrant(BaseModel):
    """
    AccessGrant model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: str
    resource_token: Annotated[str, Field(description='The token for any resource the AccessGrant is applied to.', examples=['rprt_abcd1234'])]
    access: Annotated[str, Field(description='The access status of the AccessGrant.')]
    team_token: Annotated[str | None, Field(description='The Team token for which an AccessGrant is applied to.')]
    created_at: Annotated[str, Field(description='The date and time, in UTC, the AccessGrant was created. ISO 8601 Formatted.', examples=['2023-08-04T00:00:00Z'])]
    created_by: Annotated[str | None, Field(description='The token for the User who created the AccessGrant.')]
