# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from collections.abc import Sequence
from . import access_policy_document


class AccessPolicy(BaseModel):
    """
    AccessPolicy model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: str
    title: Annotated[str, Field(description='The title of the AccessPolicy.', examples=['Engineering costs'])]
    description: Annotated[str | None, Field(description='The description of the AccessPolicy.', examples=['Limits cost visibility to the Engineering team.'])]
    policy: access_policy_document.AccessPolicyDocument
    team_tokens: Annotated[Sequence[str], Field(description='The tokens for Teams this AccessPolicy is assigned to.')]
    created_by: Annotated[str | None, Field(description='The token for the User who created the AccessPolicy.', examples=['usr_abcd1234'])]
    created_at: Annotated[str, Field(description='The date and time, in UTC, the AccessPolicy was created. ISO 8601 Formatted.', examples=['2024-01-18T17:39:37Z'])]
