# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import access_policy_document_api_version, access_policy_rules


class AccessPolicyDocument(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    api_version: Annotated[access_policy_document_api_version.AccessPolicyDocumentApiVersion, Field(description='The AccessPolicy document version.', examples=['v1'])]
    policy: access_policy_rules.AccessPolicyRules
