# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from enum import Enum


class AddTeamMemberRole(str, Enum):
    """
    The role to assign to the user. Defaults to 'editor'.
    """
    owner = 'owner'
    editor = 'editor'
    viewer = 'viewer'
    integration_owner = 'integration_owner'
