# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from . import add_team_member_role


class AddTeamMember(BaseModel):
    """
    Add a member to a Team.
    """
    user_email: Annotated[str, Field(description='The email address of the user to add to the Team.')]
    role: Annotated[add_team_member_role.AddTeamMemberRole, Field(description="The role to assign to the user. Defaults to 'editor'.")]
