# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import role2


class AddTeamMember(BaseModel):
    """
    Add a member to a Team.
    """

    user_email: Annotated[
        str, Field(description='The email address of the user to add to the Team.')
    ]
    role: Annotated[
        role2.Role,
        Field(description="The role to assign to the user. Defaults to 'editor'."),
    ]
