# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class AddTeamMemberRole(StrEnum):
    """
    The role to assign to the user. Defaults to 'editor'.
    """
    owner = 'owner'
    editor = 'editor'
    viewer = 'viewer'
    integration_owner = 'integration_owner'
