# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import adjustment_type2, calculation_type2


class AdjustmentItem(BaseModel):
    name: Annotated[str, Field(description='Name of the adjustment')]
    adjustment_type: Annotated[
        adjustment_type2.AdjustmentType, Field(description='Type of adjustment')
    ] = 'charge'
    calculation_type: Annotated[
        calculation_type2.CalculationType,
        Field(description='How the adjustment is calculated'),
    ]
    amount: Annotated[float, Field(description='Amount or percentage value')]
