# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import adjustment_item_adjustment_type, adjustment_item_calculation_type


class AdjustmentItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Annotated[str, Field(description="Name of the adjustment (e.g., 'State Tax', 'Processing Fee')")]
    adjustment_type: Annotated[adjustment_item_adjustment_type.AdjustmentItemAdjustmentType, Field(description='Type of adjustment')]
    calculation_type: Annotated[adjustment_item_calculation_type.AdjustmentItemCalculationType, Field(description='How the adjustment is calculated')]
    amount: Annotated[str, Field(description='Amount or percentage value for the adjustment')]
