# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from . import adjustment_item_adjustment_type, adjustment_item_calculation_type


class AdjustmentItem(BaseModel):
    name: Annotated[str, Field(description="Name of the adjustment (e.g., 'State Tax', 'Processing Fee')")]
    adjustment_type: Annotated[adjustment_item_adjustment_type.AdjustmentItemAdjustmentType, Field(description='Type of adjustment')]
    calculation_type: Annotated[adjustment_item_calculation_type.AdjustmentItemCalculationType, Field(description='How the adjustment is calculated')]
    amount: Annotated[str, Field(description='Amount or percentage value for the adjustment')]
