# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import adjustment_type as adjustment_type_1
from . import calculation_type as calculation_type_1


class AdjustmentItem(BaseModel):
    name: Annotated[
        str,
        Field(
            description="Name of the adjustment (e.g., 'State Tax', 'Processing Fee')"
        ),
    ]
    adjustment_type: Annotated[
        adjustment_type_1.AdjustmentType, Field(description='Type of adjustment')
    ]
    calculation_type: Annotated[
        calculation_type_1.CalculationType,
        Field(description='How the adjustment is calculated'),
    ]
    amount: Annotated[
        str, Field(description='Amount or percentage value for the adjustment')
    ]
