# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from enum import Enum


class AggregatedBy(str, Enum):
    """
    The column by which the costs are aggregated.
    """

    idle_cost = 'idle_cost'
    amount = 'amount'
    cost_efficiency = 'cost_efficiency'
