# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from collections.abc import Sequence


class Annotation(BaseModel):
    """
    Annotation model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: Annotated[str, Field(description='The unique token identifying the Annotation.')]
    title: Annotated[str, Field(description='The title of the Annotation.')]
    report_tokens: Annotated[Sequence[str], Field(description='The tokens of the Reports associated with the Annotation.')]
    date: Annotated[str | None, Field(description='The date of the Annotation. ISO 8601 formatted.', examples=['2026-08-12'])]
    message: Annotated[str | None, Field(description='The message of the Annotation.')]
