# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence

from pydantic import BaseModel

from . import anomaly_alert
from . import links as links_1


class AnomalyAlerts(BaseModel):
    """
    AnomalyAlerts model
    """

    links: links_1.Links | None = None
    anomaly_alerts: Sequence[anomaly_alert.AnomalyAlert]
