# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from pydantic import AwareDatetime, BaseModel


class AnomalyAlertsGetParametersQuery(BaseModel):
    page: int | None = None
    limit: int | None = None
    start_date: AwareDatetime | None = None
    end_date: AwareDatetime | None = None
    provider: str | None = None
    service: str | None = None
    cost_category: str | None = None
    cost_report_token: str | None = None
