# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field


class AnomalyNotification(BaseModel):
    """
    AnomalyNotification model
    """

    token: str
    cost_report_token: Annotated[
        str,
        Field(
            description='The token for the CostReport the AnomalyNotification is associated with.'
        ),
    ]
    created_at: Annotated[
        str,
        Field(
            description='The date and time, in UTC, the AnomalyNotification was created. ISO 8601 Formatted.',
            examples=['2023-08-04T00:00:00Z'],
        ),
    ]
    updated_at: Annotated[
        str,
        Field(
            description='The date and time, in UTC, the AnomalyNotification was last updated at. ISO 8601 Formatted.',
            examples=['2023-08-04T00:00:00Z'],
        ),
    ]
    threshold: Annotated[
        int,
        Field(
            description='The threshold amount that must be met for the notification to fire.'
        ),
    ]
    user_tokens: Annotated[
        Sequence[str],
        Field(description='The tokens of the users that receive the notification.'),
    ]
    recipient_channels: Annotated[
        Sequence[str],
        Field(description='The channels that the notification is sent to.'),
    ]
