# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence


class AnomalyAlert(BaseModel):
    """
    AnomalyAlert model
    """
    token: str
    created_at: Annotated[str, Field(description='The date and time, in UTC, the AnomalyAlert was created. ISO 8601 Formatted.', examples=['2021-07-09T00:00:00Z'])]
    alerted_at: Annotated[str | None, Field(description='The date and time, in UTC, the AnomalyAlert is sent. ISO 8601 Formatted.', examples=['2021-07-09T00:00:00Z'])] = None
    category: Annotated[str | None, Field(description='The category of the AnomalyAlert.')]
    service: Annotated[str, Field(description='The provider service causing the AnomalyAlert.')]
    provider: Annotated[str, Field(description='The provider of the service causing the AnomalyAlert.')]
    amount: Annotated[str, Field(description='The amount observed.')]
    previous_amount: Annotated[str, Field(description='The previous amount observed.')]
    seven_day_average: Annotated[str, Field(description='The seven day average of the amount observed.')]
    status: Annotated[str, Field(description='The status of the AnomalyAlert.')]
    feedback: Annotated[str | None, Field(description='The user-provided feedback of why alert was ignored/archived.')] = None
    resources: Annotated[Sequence[str], Field(description='The names of the resources the AnomalyAlert was attributed to.')]
    cost_report_token: Annotated[str, Field(description='The token of the Report associated with the AnomalyAlert.')]
