# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import AwareDatetime, BaseModel, ConfigDict


class AnomalyAlertsGetParametersQuery(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    page: int | None = None
    limit: int | None = None
    start_date: AwareDatetime | None = None
    end_date: AwareDatetime | None = None
    provider: str | None = None
    service: str | None = None
    cost_category: str | None = None
    cost_report_token: str | None = None
