# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence
from . import attached_business_metric_for_cost_report_unit_scale


class AttachedBusinessMetricForCostReport(BaseModel):
    business_metric_token: Annotated[str, Field(description="The token of the BusinessMetric that's attached to the CostReport.", examples=['bsnss_mtrc_1234'])]
    unit_scale: Annotated[attached_business_metric_for_cost_report_unit_scale.AttachedBusinessMetricForCostReportUnitScale, Field(description="Determines the scale of the BusinessMetric's values within a particular CostReport.", examples=['per_hundred'])]
    label_filter: Annotated[Sequence[str] | None, Field(description='The labels that the BusinessMetric is filtered by within a particular CostReport.')] = None
