# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import Enum


class AuditLogsGetParametersQueryAction(str, Enum):
    create = 'create'
    update = 'update'
    delete = 'delete'
