# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import Enum


class AuditLogsGetParametersQueryObjectType(str, Enum):
    virtual_tag = 'virtual_tag'
    cost_report = 'cost_report'
    recommendation_commitment = 'recommendation_commitment'
