# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from datetime import date
from pydantic import BaseModel
from . import audit_logs_get_parameters_query_action, audit_logs_get_parameters_query_object_type, audit_logs_get_parameters_query_source


class AuditLogsGetParametersQuery(BaseModel):
    page: int | None = None
    limit: int | None = None
    user: int | None = None
    workspace_token: str | None = None
    action: audit_logs_get_parameters_query_action.AuditLogsGetParametersQueryAction | None = None
    object_name: str | None = None
    source: audit_logs_get_parameters_query_source.AuditLogsGetParametersQuerySource | None = None
    object_type: audit_logs_get_parameters_query_object_type.AuditLogsGetParametersQueryObjectType | None = None
    token: str | None = None
    object_token: str | None = None
    start_date: date | None = None
    end_date: date | None = None
