# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated, Any
from pydantic import BaseModel, Field
from collections.abc import Mapping


class AuditLog(BaseModel):
    """
    AuditLog model
    """
    token: Annotated[str, Field(description='The unique token identifying the audit log.', examples=['adt_lg_1234567890abcdef'])]
    object_token: Annotated[str | None, Field(description='The token of the audited object.', examples=['rpt_1234567890abcdef'])]
    object_type: Annotated[str, Field(description='The type of the audited object.', examples=['Report'])]
    object_title: Annotated[str | None, Field(description='The title of the audited object.', examples=['Production Cost Report'])]
    event: Annotated[str, Field(description='The event type of the audit log.', examples=['record_created'])]
    source: Annotated[str, Field(description='The source of the action (console, api, developer).', examples=['console'])]
    user: Annotated[str | None, Field(description='The name of the user who performed the action.')] = None
    workspace_title: Annotated[str | None, Field(description='The name of the workspace associated with the audit log.')] = None
    workspace_token: Annotated[str | None, Field(description='The token of the workspace associated with the audit log.', examples=['wrkspc_1234567890abcdef'])] = None
    created_at: Annotated[str, Field(description='The date and time, in UTC, the audit log was created. ISO 8601 Formatted.', examples=['2021-07-09T00:00:00Z'])]
    changed_values: Annotated[Mapping[str, Any], Field(description='The changed values of the object.')]
    unchanged_values: Annotated[Mapping[str, Any], Field(description='The unchanged values of the object.')]
