# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import secure_data1


class BankingInformationAttributes(BaseModel):
    """
    Banking details (MSP accounts only)
    """

    token: str | None = None
    bank_name: Annotated[str | None, Field(description='Name of the bank')] = None
    beneficiary_name: Annotated[
        str | None, Field(description='Name of the account beneficiary')
    ] = None
    tax_id: Annotated[str | None, Field(description='Tax identification number')] = None
    secure_data: Annotated[
        secure_data1.SecureData | None, Field(description='Encrypted banking details')
    ] = None
