# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class BankingInformationSecureData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    account_number: Annotated[str | None, Field(description='Bank account number (US)')]
    routing_number: Annotated[str | None, Field(description='Bank routing number (US)')]
    iban: Annotated[str | None, Field(description='International Bank Account Number (EU)')]
    swift_bic: Annotated[str | None, Field(description='SWIFT/BIC code (EU)')]
