# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class BankingInformationSecureData(BaseModel):
    account_number: Annotated[str | None, Field(description='Bank account number (US)')]
    routing_number: Annotated[str | None, Field(description='Bank routing number (US)')]
    iban: Annotated[
        str | None, Field(description='International Bank Account Number (EU)')
    ]
    swift_bic: Annotated[str | None, Field(description='SWIFT/BIC code (EU)')]
