# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence


class BearerToken(BaseModel):
    description: Annotated[str, Field(description='The user supplied description of this BearerToken')]
    created_at: Annotated[str, Field(description='The date and time, in UTC, the BearerToken was created. ISO 8601 Formatted.', examples=['2023-08-04T00:00:00Z'])]
    scope: Annotated[Sequence[str], Field(description='The scopes applied to the BearerToken used to authenticate this request.')]
