# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class BillingRule(BaseModel):
    """
    BillingRule model
    """

    token: str
    title: Annotated[
        str,
        Field(
            description='The title of the BillingRule.',
            examples=['Credit for Unused EC2 Instances'],
        ),
    ]
    type: Annotated[
        str, Field(description='The type of the BillingRule.', examples=['credit'])
    ]
    start_date: Annotated[
        str | None,
        Field(
            description='The start date of the BillingRule.',
            examples=['2024-06-28T00:00:00Z'],
        ),
    ] = None
    end_date: Annotated[
        str | None,
        Field(
            description='The end date of the BillingRule.',
            examples=['2024-06-28T00:00:00Z'],
        ),
    ] = None
    apply_to_all: Annotated[
        bool,
        Field(
            description='Whether the BillingRule applies to all future managed accounts.',
            examples=[True],
        ),
    ]
    created_by_token: Annotated[
        str,
        Field(
            description='The token of the Creator of the BillingRule.',
            examples=['usr_1234'],
        ),
    ]
    created_at: Annotated[
        str,
        Field(
            description='The date and time, in UTC, the BillingRule was created. ISO 8601 Formatted.',
            examples=['2024-06-28T00:00:00Z'],
        ),
    ]
    service: Annotated[
        str | None,
        Field(
            description='The service for the BillingRule (Charge).',
            examples=['AWS Cloudfront'],
        ),
    ] = None
    category: Annotated[
        str | None,
        Field(
            description='The category for the BillingRule (Charge).',
            examples=['MSP Fee'],
        ),
    ] = None
    percentage: Annotated[
        str | None,
        Field(
            description='The percentage of the cost shown for the BillingRule (Adjustment).',
            examples=['75.0'],
        ),
    ] = None
    charge_type: Annotated[
        str | None,
        Field(description='The charge type for the BillingRule.', examples=['RIFee']),
    ] = None
    sub_category: Annotated[
        str | None,
        Field(
            description='The subcategory for the BillingRule (Charge).',
            examples=['One-time'],
        ),
    ] = None
    start_period: Annotated[
        str | None,
        Field(
            description='The start period for the BillingRule (Charge).',
            examples=['2024-05-01'],
        ),
    ] = None
    amount: Annotated[
        str | None,
        Field(
            description='The amount for the BillingRule (Charge).', examples=['5000.25']
        ),
    ] = None
    sql_query: Annotated[
        str | None,
        Field(
            description='The SQL query for the BillingRule (Custom).',
            examples=['UPDATE costs SET costs.amount = costs.amount * 0.95'],
        ),
    ] = None
