# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from . import banking_information, billing_information, business_information, invoice_adjustment


class BillingProfile(BaseModel):
    """
    BillingProfile model
    """
    token: str
    nickname: Annotated[str, Field(description='Display name for the billing profile')]
    created_at: Annotated[str, Field(description='The date and time, in UTC, the billing profile was created. ISO 8601 formatted.', examples=['2023-08-04T00:00:00Z'])]
    updated_at: Annotated[str, Field(description='The date and time, in UTC, the billing profile was last updated. ISO 8601 formatted.', examples=['2023-08-04T00:00:00Z'])]
    billing_information_attributes: billing_information.BillingInformation
    business_information_attributes: business_information.BusinessInformation
    banking_information_attributes: banking_information.BankingInformation | None = None
    invoice_adjustment_attributes: invoice_adjustment.InvoiceAdjustment
    managed_accounts_count: Annotated[str, Field(description='Number of managed accounts using this billing profile')]
