# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel, ConfigDict
from . import billing_rule, links as links_1


class BillingRules(BaseModel):
    """
    BillingRules model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    links: links_1.Links | None = None
    billing_rules: Sequence[billing_rule.BillingRule]
