# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel, ConfigDict
from . import billing_profile, links as links_1


class BillingProfiles(BaseModel):
    """
    BillingProfiles model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    links: links_1.Links | None = None
    billing_profiles: Sequence[billing_profile.BillingProfile]
