# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel
from . import budget_alert, links as links_1


class BudgetAlerts(BaseModel):
    """
    BudgetAlerts model
    """
    links: links_1.Links | None = None
    budget_alerts: Sequence[budget_alert.BudgetAlert]
