# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field


class BudgetAlert(BaseModel):
    """
    BudgetAlert model
    """

    token: str
    budget_tokens: Annotated[
        Sequence[str],
        Field(
            description='The tokens for the Budgets that the Budget Alert is monitoring to trigger alerts on.'
        ),
    ]
    created_at: Annotated[
        str,
        Field(
            description='The date and time, in UTC, the Budget Alert was created. ISO 8601 Formatted.',
            examples=['2024-03-19T00:00:00Z'],
        ),
    ]
    workspace_token: Annotated[
        str,
        Field(
            description='The token for the Workspace the ResourceReport is a part of.'
        ),
    ]
    user_token: Annotated[
        str | None,
        Field(description='The token for the User who created this BudgetAlert.'),
    ] = None
    user_tokens: Annotated[
        Sequence[str], Field(description='The Users that receive the alert.')
    ]
    duration_in_days: Annotated[
        str | None,
        Field(
            description='The number of days from the start or end of the month to trigger the alert if the threshold is reached.'
        ),
    ]
    threshold: Annotated[
        int,
        Field(
            description='Alerts only send if they reach this number (as a percentage). When threshold is 100, that means alerts are triggered once costs reach 100% of the budget.',
            examples=[75],
        ),
    ]
    period_to_track: Annotated[
        str | None,
        Field(
            description='The period tracked on the alert. Used with duration_in_days to determine the time window of the alert. Possible values: start_of_the_month, end_of_the_month.',
            examples=['start_of_the_month'],
        ),
    ]
    integration_provider: Annotated[
        str | None,
        Field(
            description='The provider used for sending alerts. This must be configured in the console. Possible values are: slack, microsoft_graph.',
            examples=['slack'],
        ),
    ] = None
    recipient_channels: Annotated[
        str,
        Field(
            description='The channels receiving the alerts. Requires an integration provider to be connected.',
            examples=[''],
        ),
    ]
