# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class BudgetPerformance(BaseModel):
    date: Annotated[
        str,
        Field(
            description='The date and time, in UTC, the Budget was created. ISO 8601 Formatted.',
            examples=['2024-03-19T00:00:00Z'],
        ),
    ]
    actual: Annotated[
        str,
        Field(
            description='The date and time, in UTC, the Budget was created. ISO 8601 Formatted.',
            examples=['2024-03-19T00:00:00Z'],
        ),
    ]
    amount: Annotated[
        str,
        Field(
            description='The amount of the Budget Period as a string to ensure precision.',
            examples=['100.00'],
        ),
    ]
