# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence

from pydantic import BaseModel

from . import budget
from . import links as links_1


class Budgets(BaseModel):
    """
    Budgets model
    """

    links: links_1.Links | None = None
    budgets: Sequence[budget.Budget]
