# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from collections.abc import Sequence
from typing import Annotated
from pydantic import BaseModel, Field
from . import business_information_custom_field


class BusinessInformationMetadata(BaseModel):
    custom_fields: Annotated[Sequence[business_information_custom_field.BusinessInformationCustomField] | None, Field(description='Array of custom field objects')] = None
