# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import metadata2


class BusinessInformationAttributes(BaseModel):
    """
    Business information and custom fields (MSP invoicing accounts only)
    """

    id: int | None = None
    token: str | None = None
    metadata: Annotated[
        metadata2.Metadata | None,
        Field(description='Business metadata including custom fields'),
    ] = None
