# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict


class BusinessMetricsBusinessMetricTokenLabelsGetParametersQuery(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    page: int = 1
    limit: int = 1000
