# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class BusinessMetricImportType(StrEnum):
    """
    The type of import for the BusinessMetric.
    """
    datadog_metrics = 'datadog_metrics'
    cloudwatch = 'cloudwatch'
    snowflake_metrics = 'snowflake_metrics'
    metronome_metrics = 'metronome_metrics'
    csv = 'csv'
