# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from datetime import date
from collections.abc import Sequence
from . import business_metrics_business_metric_token_values_get_parameters_query_date_bin


class BusinessMetricsBusinessMetricTokenValuesGetParametersQuery(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    page: int | None = None
    limit: Annotated[int | None, Field(ge=1, le=5000)] = None
    start_date: date | None = None
    label_values: Sequence[str] | None = None
    date_bin: business_metrics_business_metric_token_values_get_parameters_query_date_bin.BusinessMetricsBusinessMetricTokenValuesGetParametersQueryDateBin | None = None
