# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from datetime import date

from pydantic import BaseModel


class BusinessMetricsBusinessMetricTokenValuesGetParametersQuery(BaseModel):
    page: int | None = None
    limit: int | None = None
    start_date: date | None = None
