# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence
from . import attached_cost_report_for_business_metric, business_metric_import_type, cloudwatch_fields as cloudwatch_fields_1, datadog_metric_fields as datadog_metric_fields_1


class BusinessMetric(BaseModel):
    """
    BusinessMetric model
    """
    token: Annotated[str, Field(description='The token of the BusinessMetric.', examples=['bsnss_mtrc_1234'])]
    title: Annotated[str, Field(description='The title of the BusinessMetric.', examples=['Total Revenue'])]
    created_by_token: Annotated[str | None, Field(description='The token of the Creator of the BusinessMetric.', examples=['usr_1234'])] = None
    cost_report_tokens_with_metadata: Annotated[Sequence[attached_cost_report_for_business_metric.AttachedCostReportForBusinessMetric], Field(description='The tokens for any CostReports that use the BusinessMetric, the unit scale, and label filter.')]
    import_type: Annotated[business_metric_import_type.BusinessMetricImportType, Field(description='The type of import for the BusinessMetric.', examples=['datadog_metrics'])]
    integration_token: Annotated[str | None, Field(description='The Integration token used to import the BusinessMetric.')]
    cloudwatch_fields: cloudwatch_fields_1.CloudwatchFields | None = None
    datadog_metric_fields: datadog_metric_fields_1.DatadogMetricFields | None = None
