# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict


class BusinessMetricsBusinessMetricTokenValuesDeleteParametersQuery(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    start_date: str | None = None
    end_date: str | None = None
    label: str | None = None
    forecasted: bool = False
