# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import BaseModel
from . import business_information_metadata


class BusinessInformation(BaseModel):
    token: str
    metadata: business_information_metadata.BusinessInformationMetadata | None = None
