# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class BusinessMetricsBusinessMetricTokenValuesCsvPutRequest(BaseModel):
    csv: Annotated[
        bytes, Field(description='CSV file containing BusinessMetric dates and amounts')
    ]
    forecasted: Annotated[
        bool,
        Field(
            description='When true, imports values as forecasted metrics instead of historical metrics.'
        ),
    ] = False
