# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel, ConfigDict
from . import business_metric


class BusinessMetrics(BaseModel):
    """
    BusinessMetrics model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    business_metrics: Sequence[business_metric.BusinessMetric]
