# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import Enum


class BusinessMetricImportType(str, Enum):
    """
    The type of import for the BusinessMetric.
    """
    datadog_metrics = 'datadog_metrics'
    cloudwatch = 'cloudwatch'
    csv = 'csv'
