# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class BusinessInformationCustomField(BaseModel):
    name: Annotated[str, Field(description='Custom field name')]
    value: Annotated[str | None, Field(description='Custom field value')]
