# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel
from . import business_metric


class BusinessMetrics(BaseModel):
    """
    BusinessMetrics model
    """
    business_metrics: Sequence[business_metric.BusinessMetric]
