# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field

from . import unit_scale4


class BusinessMetricTokensWithMetadatum(BaseModel):
    business_metric_token: Annotated[
        str,
        Field(
            description='The token of the BusinessMetric to attach to the CostReport.'
        ),
    ]
    unit_scale: Annotated[
        unit_scale4.UnitScale,
        Field(
            description="Determines the scale of the BusinessMetric's values within the CostReport."
        ),
    ] = 'per_unit'
    label_filter: Annotated[
        Sequence[str] | None,
        Field(description='Include only values with these labels in the CostReport.'),
    ] = None
