# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import metadata1


class BusinessInformationAttributes(BaseModel):
    """
    Business information and custom fields
    """

    token: str | None = None
    metadata: Annotated[
        metadata1.Metadata | None,
        Field(description='Business metadata including custom fields'),
    ] = None
