# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class BusinessMetricValue(BaseModel):
    date: Annotated[
        str,
        Field(
            description='The date of the Business Metric Value. ISO 8601 formatted.',
            examples=['2024-03-01+00:00'],
        ),
    ]
    amount: Annotated[
        str,
        Field(
            description='The amount of the Business Metric Value as a string to ensure precision.',
            examples=['100.00'],
        ),
    ]
    label: Annotated[
        str | None,
        Field(
            description='The label of the Business Metric Value.',
            examples=['Cost Center A'],
        ),
    ] = None
