# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class CanvasStatus(StrEnum):
    """
    The status of the Canvas.
    """
    draft = 'draft'
    published = 'published'
