# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import canvas_data


class Canvas(BaseModel):
    """
    Canvas model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: Annotated[str, Field(examples=['cnvs_abcd1234567890'])]
    title: Annotated[str, Field(description='The title of the Canvas.', examples=['Weekly Spend by Team'])]
    prompt: Annotated[str, Field(description='The prompt used to generate the Canvas.')]
    data: canvas_data.CanvasData | None = None
    workspace_token: Annotated[str, Field(description='The token for the Workspace the Canvas belongs to.', examples=['wrkspc_abcd1234567890'])]
    created_at: Annotated[str, Field(description='The date and time, in UTC, the Canvas was created. ISO 8601 Formatted.', examples=['2024-01-01T00:00:00Z'])]
    updated_at: Annotated[str, Field(description='The date and time, in UTC, the Canvas was last updated. ISO 8601 Formatted.', examples=['2024-01-01T00:00:00Z'])]
