# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import canvas_table


class CanvasData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    table: canvas_table.CanvasTable | None = None
    error: Annotated[str | None, Field(description='Error message if the refresh workflow failed. Read-only.')] = None
