# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class ClickhouseMetricFields(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    query_endpoint_id: Annotated[str, Field(description='The UUID of the ClickHouse query endpoint used to import metrics.', examples=['7c6a3a87-12fd-41f5-afdf-caa4697a2886'])]
