# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field

from . import cloudwatch_dimension
from . import stat as stat_1


class CloudwatchFields(BaseModel):
    stat: Annotated[
        stat_1.Stat,
        Field(
            description='The time aggregation function used to import Cloudwatch metrics.',
            examples=['Average'],
        ),
    ]
    region: Annotated[
        str,
        Field(
            description='The region used to import Cloudwatch metrics.',
            examples=['us-east-1'],
        ),
    ]
    namespace: Annotated[
        str,
        Field(
            description='The namespace used to import Cloudwatch metrics.',
            examples=['AWS/EC2'],
        ),
    ]
    metric_name: Annotated[
        str,
        Field(
            description='The metric name used to import Cloudwatch metrics.',
            examples=['CPUUtilization'],
        ),
    ]
    dimensions: Annotated[
        Sequence[cloudwatch_dimension.CloudwatchDimension],
        Field(
            description='The dimensions used to pull specific statistical data for Cloudwatch metrics.'
        ),
    ]
    label_dimension: Annotated[
        str | None,
        Field(description='The dimension used to aggregate the Cloudwatch metrics.'),
    ]
