# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from enum import Enum


class CloudwatchFieldsStat(str, Enum):
    """
    The time aggregation function used to import Cloudwatch metrics.
    """
    Sum = 'Sum'
    Average = 'Average'
    Minimum = 'Minimum'
    Maximum = 'Maximum'
