# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import BaseModel


class CloudwatchDimension(BaseModel):
    name: str
    value: str
