# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field

from . import dimension1


class CloudwatchFields(BaseModel):
    """
    Cloudwatch configuration fields.
    """

    integration_token: Annotated[
        str | None,
        Field(
            description='Integration token for the account from which you would like to fetch metrics.'
        ),
    ] = None
    stat: str | None = None
    region: str | None = None
    namespace: str | None = None
    metric_name: str | None = None
    label_dimension: str | None = None
    dimensions: Sequence[dimension1.Dimension] | None = None
