# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from pydantic import BaseModel


class CostReportsGetParametersQuery(BaseModel):
    page: int | None = None
    limit: int | None = None
    folder_token: str | None = None
