# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class CostReportUrl(BaseModel):
    """
    CostReportUrl model
    """
    cost_report_url: Annotated[str, Field(description='The URL of the cost report.', examples=['https://example.com/cost_report.pdf'])]
