# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from datetime import date
from pydantic import BaseModel, ConfigDict
from . import cost_reports_cost_report_token_forecasted_costs_get_parameters_query_provider


class CostReportsCostReportTokenForecastedCostsGetParametersQuery(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    start_date: date | None = None
    end_date: date | None = None
    provider: cost_reports_cost_report_token_forecasted_costs_get_parameters_query_provider.CostReportsCostReportTokenForecastedCostsGetParametersQueryProvider | None = None
    service: str | None = None
    page: int | None = None
    limit: int | None = None
