# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence

from pydantic import BaseModel

from . import cost_service
from . import links as links_1


class CostServices(BaseModel):
    """
    CostServices model
    """

    links: links_1.Links | None = None
    cost_services: Sequence[cost_service.CostService]
