# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class CostReportSettingsAggregateBy(StrEnum):
    """
    Report will aggregate by cost, usage, or count.
    """
    cost = 'cost'
    usage = 'usage'
    count_ = 'count'
