# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence
from . import attached_business_metric_for_cost_report, chart_settings as chart_settings_1, cost_report_settings


class CostReport(BaseModel):
    """
    CostReport model
    """
    token: str
    title: Annotated[str, Field(description='The title of the CostReport.', examples=['Production Environment'])]
    folder_token: Annotated[str | None, Field(description='The token for the Folder the CostReport is a part of.')] = None
    saved_filter_tokens: Annotated[Sequence[str] | None, Field(description='The tokens for the SavedFilters assigned to the CostReport.')] = None
    business_metric_tokens_with_metadata: Annotated[Sequence[attached_business_metric_for_cost_report.AttachedBusinessMetricForCostReport], Field(description='The tokens for the BusinessMetrics assigned to the CostReport, the unit scale, and label filter.')]
    filter: Annotated[str | None, Field(description='The filter applied to the CostReport. Additional documentation available at https://docs.vantage.sh/vql.')]
    groupings: Annotated[str | None, Field(description='The grouping aggregations applied to the filtered data.', examples=['provider, service'])] = None
    settings: Annotated[cost_report_settings.CostReportSettings | None, Field(description='Report settings.')] = None
    created_at: Annotated[str, Field(description='The date and time, in UTC, the report was created. ISO 8601 Formatted.', examples=['2021-07-09T00:00:00Z'])]
    workspace_token: Annotated[str, Field(description='The token for the Workspace the CostReport is a part of.')]
    previous_period_start_date: Annotated[str | None, Field(description='The previous period start date of the CostReport. ISO 8601 Formatted.', examples=['2024-06-01'])] = None
    previous_period_end_date: Annotated[str | None, Field(description='The previous period end date of the CostReport. ISO 8601 Formatted.', examples=['2024-06-15'])] = None
    start_date: Annotated[str | None, Field(description="The start date of the CostReports. ISO 8601 Formatted. Overwrites 'date_interval' if set.", examples=['2024-07-01'])] = None
    end_date: Annotated[str | None, Field(description="The end date of the CostReports. ISO 8601 Formatted. Overwrites 'date_interval' if set.", examples=['2024-07-15'])] = None
    date_interval: Annotated[str, Field(description='The date interval of the CostReport.')]
    chart_type: Annotated[str, Field(description='The chart type of the CostReport.')]
    date_bin: Annotated[str, Field(description='The date bin of the CostReport.')]
    chart_settings: chart_settings_1.ChartSettings
