# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Annotated, Any

from pydantic import BaseModel, Field

from . import links as links_1
from . import provider1


class Cost(BaseModel):
    """
    Cost model
    """

    links: links_1.Links | None = None
    accrued_at: Annotated[
        str,
        Field(
            description='The date the cost was accrued. ISO 8601 Formatted.',
            examples=['2023-09-05+00:00'],
        ),
    ]
    amount: Annotated[
        str, Field(description='The amount of the cost.', examples=['4.25'])
    ]
    currency: Annotated[
        str, Field(description='The currency of the cost.', examples=['USD'])
    ]
    usage: Annotated[
        Mapping[str, Any] | None,
        Field(description='The usage amount and unit incurred by the cost.'),
    ] = None
    provider: Annotated[
        provider1.Provider | None,
        Field(
            description='The cost provider which incurred the cost.', examples=['aws']
        ),
    ] = None
    billing_account_id: Annotated[
        str | None,
        Field(
            description="The cost provider's billing account id that incurred the cost.",
            examples=['9109237192'],
        ),
    ] = None
    account_id: Annotated[
        str | None,
        Field(
            description="The cost provider's account id that incurred the cost.",
            examples=['9109237192'],
        ),
    ] = None
    service: Annotated[
        str | None,
        Field(
            description='The service which incurred the cost.',
            examples=['Amazon Elastic Compute Cloud - Compute'],
        ),
    ] = None
    region: Annotated[
        str | None,
        Field(
            description='The region which incurred the cost.', examples=['us-east-1']
        ),
    ] = None
    resource_id: Annotated[
        str | None,
        Field(
            description='The resource id which incurred the cost.',
            examples=[
                'arn:aws:ec2:us-east-1:123456789012:instance/i-1234567890abcdef0'
            ],
        ),
    ] = None
    tag: Annotated[
        str | None,
        Field(
            description='The tag attached to the cost that was incurred.\nDEPRECATED: does not support multiple tags.',
            examples=['production'],
        ),
    ] = None
    tags: Annotated[
        Sequence[str] | None,
        Field(description='The tag pairs attached to the cost that was incurred.'),
    ] = None
    cost_category: Annotated[
        str | None,
        Field(description='The category for the cost.', examples=['Data Transfer']),
    ] = None
    cost_subcategory: Annotated[
        str | None,
        Field(
            description='The subcategory for the cost.',
            examples=['DataTransfer-Regional-Bytes'],
        ),
    ] = None
    segment: Annotated[
        str | None,
        Field(
            description='The segment name for segment report costs.',
            examples=['Engineering'],
        ),
    ] = None
