# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class CostsGetParametersQuerySettingsAggregateBy(StrEnum):
    cost = 'cost'
    usage = 'usage'
    count_ = 'count'
