# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class CostProviderAccount(BaseModel):
    title: Annotated[str, Field(description='The display name of the provider account.', examples=['Production Account'])]
    account_id: Annotated[str, Field(description='The provider account identifier (e.g., AWS account ID, Azure subscription ID).', examples=['123456789012'])]
    provider_uuid: Annotated[str, Field(description='The provider-specific unique identifier.', examples=['arn:aws:organizations::123456789012:account/o-example12345/123456789012'])]
    provider: Annotated[str, Field(description='The provider type (aws, azure, gcp, etc.).', examples=['aws'])]
