# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import provider2


class CostProviderAccountsGetParametersQuery(BaseModel):
    workspace_token: str | None = None
    provider: provider2.Provider | None = None
    account_id: str | None = None
    account_name: str | None = None
