# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import BaseModel


class CostAlertsCostAlertTokenEventsGetParametersQuery(BaseModel):
    report_token: str | None = None
    page: int | None = None
    limit: int | None = None
