# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class CostPartial(BaseModel):
    amount: Annotated[str, Field(description='The amount of the cost.', examples=['4.25'])]
    currency: Annotated[str, Field(description='The currency of the cost.', examples=['USD'])]
