# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel
from . import cost_alert_event, links as links_1


class CostAlertEvents(BaseModel):
    """
    CostAlertEvents model
    """
    links: links_1.Links | None = None
    cost_alert_events: Sequence[cost_alert_event.CostAlertEvent]
