# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from enum import Enum


class CostReportsCostReportTokenForecastedCostsGetParametersQueryProvider(str, Enum):
    aws = 'aws'
    azure = 'azure'
    gcp = 'gcp'
    snowflake = 'snowflake'
    databricks = 'databricks'
    mongo = 'mongo'
    datadog = 'datadog'
    fastly = 'fastly'
    new_relic = 'new_relic'
    opencost = 'opencost'
    open_ai = 'open_ai'
    oracle = 'oracle'
    confluent = 'confluent'
    planetscale = 'planetscale'
    coralogix = 'coralogix'
    kubernetes = 'kubernetes'
    custom_provider = 'custom_provider'
    github = 'github'
    linode = 'linode'
    grafana = 'grafana'
    clickhouse = 'clickhouse'
    temporal = 'temporal'
    twilio = 'twilio'
    azure_csp = 'azure_csp'
    kubernetes_agent = 'kubernetes_agent'
    anthropic = 'anthropic'
    anyscale = 'anyscale'
    cursor = 'cursor'
    elastic = 'elastic'
    vercel = 'vercel'
    all = 'all'
