# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import costs_get_parameters_query_date_bin, costs_get_parameters_query_order, costs_get_parameters_query_settings_aggregate_by


class CostsGetParametersQuery(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    cost_report_token: str | None = None
    filter: str | None = None
    workspace_token: str | None = None
    start_date: str | None = None
    end_date: str | None = None
    groupings: Sequence[str] | None = None
    order: costs_get_parameters_query_order.CostsGetParametersQueryOrder = costs_get_parameters_query_order.CostsGetParametersQueryOrder.desc
    limit: int | None = None
    page: int | None = None
    date_bin: costs_get_parameters_query_date_bin.CostsGetParametersQueryDateBin | None = None
    settings_include_credits_: Annotated[bool | None, Field(alias='settings[include_credits]')] = None
    settings_include_refunds_: Annotated[bool | None, Field(alias='settings[include_refunds]')] = None
    settings_include_discounts_: Annotated[bool | None, Field(alias='settings[include_discounts]')] = None
    settings_include_tax_: Annotated[bool | None, Field(alias='settings[include_tax]')] = None
    settings_amortize_: Annotated[bool | None, Field(alias='settings[amortize]')] = None
    settings_unallocated_: Annotated[bool | None, Field(alias='settings[unallocated]')] = None
    settings_aggregate_by_: Annotated[costs_get_parameters_query_settings_aggregate_by.CostsGetParametersQuerySettingsAggregateBy | None, Field(alias='settings[aggregate_by]')] = None
    settings_show_previous_period_: Annotated[bool | None, Field(alias='settings[show_previous_period]')] = None
