# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field

from . import date_bin8
from . import order as order_1


class CostsGetParametersQuery(BaseModel):
    cost_report_token: str | None = None
    filter: str | None = None
    workspace_token: str | None = None
    start_date: str | None = None
    end_date: str | None = None
    groupings: Sequence[str] | None = None
    order: order_1.Order = 'desc'
    limit: int | None = None
    page: int | None = None
    date_bin: date_bin8.DateBin | None = None
    settings_include_credits_: Annotated[
        bool, Field(alias='settings[include_credits]')
    ] = False
    settings_include_refunds_: Annotated[
        bool, Field(alias='settings[include_refunds]')
    ] = False
    settings_include_discounts_: Annotated[
        bool, Field(alias='settings[include_discounts]')
    ] = True
    settings_include_tax_: Annotated[bool, Field(alias='settings[include_tax]')] = True
    settings_amortize_: Annotated[bool, Field(alias='settings[amortize]')] = True
    settings_unallocated_: Annotated[bool, Field(alias='settings[unallocated]')] = False
    settings_aggregate_by_: Annotated[str, Field(alias='settings[aggregate_by]')] = (
        'cost'
    )
    settings_show_previous_period_: Annotated[
        bool, Field(alias='settings[show_previous_period]')
    ] = True
