# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class CostService(BaseModel):
    name: Annotated[
        str,
        Field(
            description='The name of the CostService.',
            examples=['Amazon Simple Storage Service'],
        ),
    ]
    provider: Annotated[
        str, Field(description='The key value of the CostProvider.', examples=['aws'])
    ]
