# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Mapping
from typing import Annotated, Any

from pydantic import BaseModel, Field


class CostAlertEvent(BaseModel):
    """
    CostAlertEvent model
    """

    token: str
    created_at: Annotated[
        str,
        Field(
            description='The date and time, in UTC, the CostAlertEvent was created. ISO 8601 Formatted.',
            examples=['2021-07-09T00:00:00Z'],
        ),
    ]
    triggered_at: Annotated[
        str,
        Field(
            description='The date and time, in UTC, the CostAlertEvent is sent. ISO 8601 Formatted.',
            examples=['2021-07-09T00:00:00Z'],
        ),
    ]
    description: Annotated[
        str, Field(description='The description of the CostAlertEvent.')
    ]
    alert_type: Annotated[str, Field(description='The type of the CostAlertEvent.')]
    metadata: Annotated[
        Mapping[str, Any], Field(description='The metadata of the CostAlertEvent.')
    ]
    report_token: Annotated[
        str,
        Field(
            description='The token of the report associated with the CostAlertEvent.'
        ),
    ]
    alert_token: Annotated[
        str,
        Field(description='The token of the alert associated with the CostAlertEvent.'),
    ]
