# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import aggregation as aggregation_1


class CostMetric(BaseModel):
    filter: str
    aggregation: aggregation_1.Aggregation
