# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel, ConfigDict
from . import cost_provider_account, links as links_1


class CostProviderAccounts(BaseModel):
    """
    CostProviderAccounts model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    links: links_1.Links | None = None
    cost_provider_accounts: Sequence[cost_provider_account.CostProviderAccount]
