# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel, ConfigDict
from . import cost_alert_event, links as links_1


class CostAlertEvents(BaseModel):
    """
    CostAlertEvents model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    links: links_1.Links | None = None
    cost_alert_events: Sequence[cost_alert_event.CostAlertEvent]
