# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class CostCount(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    accrued_at: Annotated[str, Field(description='The date bin for the count. ISO 8601 Formatted.', examples=['2023-09-05+00:00'])]
    count: Annotated[int, Field(description='The number of distinct Group By permutations carrying cost in the date bin.', examples=[2])]
