# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from datetime import date
from typing import Annotated

from pydantic import BaseModel, Field

from . import collapsed_tag_key, value2


class CreateVirtualTagConfig(BaseModel):
    """
    Create a new VirtualTagConfig.
    """

    key: Annotated[str, Field(description='The key of the VirtualTagConfig.')]
    overridable: Annotated[
        bool,
        Field(
            description='Whether the VirtualTagConfig can override a provider-supplied tag on a matching Cost.'
        ),
    ]
    backfill_until: Annotated[
        date | None,
        Field(
            description='The earliest month the VirtualTagConfig should be backfilled to.'
        ),
    ] = None
    collapsed_tag_keys: Annotated[
        Sequence[collapsed_tag_key.CollapsedTagKey] | None,
        Field(description='Tag keys to collapse values for.'),
    ] = None
    values: Annotated[
        Sequence[value2.Value] | None,
        Field(
            description='Values for the VirtualTagConfig, with match precedence determined by order in the list.'
        ),
    ] = None
