# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class CreateUserFeedback(BaseModel):
    """
    Provide UserFeedback for our product and features.
    """

    message: Annotated[str, Field(description='UserFeedback message')]
