# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import report_settings1


class CreateSegment(BaseModel):
    """
    Create a Segment.
    """

    title: Annotated[str, Field(description='The title of the Segment.')]
    description: Annotated[
        str | None, Field(description='The description of the Segment.')
    ] = None
    priority: Annotated[
        int | None, Field(description='The priority of the Segment.')
    ] = None
    track_unallocated: Annotated[
        bool,
        Field(
            description='Track Unallocated Costs which are not assigned to any of the created Segments.'
        ),
    ] = False
    report_settings: Annotated[
        report_settings1.ReportSettings | None,
        Field(description='Report settings configurable on top-level Segments.'),
    ] = None
    workspace_token: Annotated[
        str | None,
        Field(
            description="The token of the Workspace to add the Segment to. Ignored if 'segment_token' is set. Required if the API token is associated with multiple Workspaces."
        ),
    ] = None
    filter: Annotated[
        str | None,
        Field(
            description='The filter query language to apply to the Segment. Additional documentation available at https://docs.vantage.sh/vql.'
        ),
    ] = None
    parent_segment_token: Annotated[
        str | None,
        Field(
            description='The token of the parent Segment this new Segment belongs to. Determines the Workspace the segment is assigned to.'
        ),
    ] = None
