# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence
from . import create_team_role


class CreateTeam(BaseModel):
    """
    Create a new Team.
    """
    name: Annotated[str, Field(description='The name of the Team.')]
    description: Annotated[str | None, Field(description='The description of the Team.')] = None
    workspace_tokens: Annotated[Sequence[str] | None, Field(description='The Workspace tokens to associate to the Team.')] = None
    user_tokens: Annotated[Sequence[str] | None, Field(description='The User tokens to associate to the Team.')] = None
    user_emails: Annotated[Sequence[str] | None, Field(description='The User emails to associate to the Team.')] = None
    role: Annotated[create_team_role.CreateTeamRole | None, Field(description="The role to assign to the provided Users. Defaults to 'editor' which has editor permissions.")] = None
    default_dashboard_token: Annotated[str | None, Field(description='The token of a Dashboard to set as the Team default. Send null to clear.')] = None
