# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class CreateUserFeedback(BaseModel):
    """
    Provide UserFeedback for our product and features.
    """
    message: Annotated[str, Field(description='UserFeedback message')]
