# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from enum import Enum


class CreateUnitCostsExportDateBin(str, Enum):
    """
    The date bin of the unit costs. Defaults to the report's default or day.
    """
    day = 'day'
    week = 'week'
    month = 'month'
    quarter = 'quarter'
