# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import exchange_rate_date as exchange_rate_date_1


class CreateWorkspace(BaseModel):
    """
    Create a workspace
    """

    name: Annotated[str, Field(description='Name of the workspace.')]
    enable_currency_conversion: Annotated[
        bool, Field(description='Enable currency conversion for the workspace.')
    ] = True
    currency: Annotated[
        str | None, Field(description='Currency code for the workspace.')
    ] = None
    exchange_rate_date: Annotated[
        exchange_rate_date_1.ExchangeRateDate,
        Field(description='The date to use for currency conversion.'),
    ] = 'daily_rate'
