# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from datetime import date
from collections.abc import Sequence
from . import create_financial_commitment_report_date_bucket, create_financial_commitment_report_date_interval, create_financial_commitment_report_on_demand_costs_scope


class CreateFinancialCommitmentReport(BaseModel):
    """
    Create a FinancialCommitmentReport.
    """
    workspace_token: Annotated[str, Field(description='The Workspace in which the FinancialCommitmentReport will be created.')]
    title: Annotated[str, Field(description='The title of the FinancialCommitmentReport.')]
    filter: Annotated[str | None, Field(description='The filter query language to apply to the FinancialCommitmentReport. Additional documentation available at https://docs.vantage.sh/vql.')] = None
    start_date: Annotated[date | None, Field(description="The start date of the FinancialCommitmentReport. YYYY-MM-DD formatted. Incompatible with 'date_interval' parameter.", examples=['2024-03-01'])] = None
    end_date: Annotated[date | None, Field(description="The end date of the FinancialCommitmentReport. YYYY-MM-DD formatted. Incompatible with 'date_interval' parameter.", examples=['2024-03-01'])] = None
    date_interval: Annotated[create_financial_commitment_report_date_interval.CreateFinancialCommitmentReportDateInterval | None, Field(description="The date interval of the FinancialCommitmentReport. Unless 'custom' is used, this is incompatible with 'start_date' and 'end_date' parameters. Defaults to 'last_3_months'.")] = None
    date_bucket: Annotated[create_financial_commitment_report_date_bucket.CreateFinancialCommitmentReportDateBucket | None, Field(description='The date bucket of the FinancialCommitmentReport.')] = None
    on_demand_costs_scope: Annotated[create_financial_commitment_report_on_demand_costs_scope.CreateFinancialCommitmentReportOnDemandCostsScope | None, Field(description='The scope for the costs. Possible values: discountable, all.')] = None
    groupings: Annotated[Sequence[str] | None, Field(description='Grouping values for aggregating costs on the FinancialCommitmentReport. Valid groupings: cost_type, commitment_type, commitment_id, service, resource_account_id, provider_account_id, region, cost_category, cost_sub_category, instance_type, tag, tag:<label_name>.')] = None
