# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from enum import Enum


class CreateCostReportDateBin(str, Enum):
    """
    The date bin of the CostReport.
    """
    cumulative = 'cumulative'
    day = 'day'
    week = 'week'
    month = 'month'
    quarter = 'quarter'
