# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from collections.abc import Sequence
from . import create_cost_report_business_metric_tokens_with_metadatum_unit_scale


class CreateCostReportBusinessMetricTokensWithMetadatum(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    business_metric_token: Annotated[str, Field(description='The token of the BusinessMetric to attach to the CostReport.')]
    unit_scale: Annotated[create_cost_report_business_metric_tokens_with_metadatum_unit_scale.CreateCostReportBusinessMetricTokensWithMetadatumUnitScale, Field(description="Determines the scale of the BusinessMetric's values within the CostReport.")] = create_cost_report_business_metric_tokens_with_metadatum_unit_scale.CreateCostReportBusinessMetricTokensWithMetadatumUnitScale.per_unit
    label_filter: Annotated[Sequence[str] | None, Field(description='Include only values with these labels in the CostReport.')] = None
