# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import BaseModel


class CreateVirtualTagConfigValuePercentage(BaseModel):
    value: str
    pct: float
