# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence
from . import create_business_metric_cost_report_tokens_with_metadatum_unit_scale


class CreateBusinessMetricCostReportTokensWithMetadatum(BaseModel):
    cost_report_token: Annotated[str, Field(description='The token of the CostReport the BusinessMetric is attached to.')]
    unit_scale: Annotated[create_business_metric_cost_report_tokens_with_metadatum_unit_scale.CreateBusinessMetricCostReportTokensWithMetadatumUnitScale, Field(description="Determines the scale of the BusinessMetric's values within the CostReport.")] = 'per_unit'
    label_filter: Annotated[Sequence[str] | None, Field(description='Include only values with these labels in the CostReport.')] = None
