# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class CreateAzureIntegration(BaseModel):
    """
    Create an Azure Integration
    """
    tenant: Annotated[str, Field(description='Azure AD Tenant ID.')]
    app_id: Annotated[str, Field(description='Service Principal Application ID.')]
    password: Annotated[str, Field(description='Service Principal Password.')]
