# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from enum import Enum


class CreateDashboardDateInterval(str, Enum):
    """
    Determines the date range in the Dashboard. Incompatible with 'start_date' and 'end_date' parameters.
    """
    this_month = 'this_month'
    last_7_days = 'last_7_days'
    last_30_days = 'last_30_days'
    last_month = 'last_month'
    last_3_months = 'last_3_months'
    last_6_months = 'last_6_months'
    custom = 'custom'
    last_12_months = 'last_12_months'
    last_24_months = 'last_24_months'
    last_36_months = 'last_36_months'
    next_month = 'next_month'
    next_3_months = 'next_3_months'
    next_6_months = 'next_6_months'
    next_12_months = 'next_12_months'
    year_to_date = 'year_to_date'
    last_3_days = 'last_3_days'
    last_14_days = 'last_14_days'
