# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field

from . import date_bin4, date_interval3, widget


class CreateDashboard(BaseModel):
    """
    Create a Dashboard.
    """

    title: Annotated[str, Field(description='The title of the Dashboard.')]
    widgets: Annotated[
        Sequence[widget.Widget] | None,
        Field(
            description='The widgets to add to the Dashboard. Currently supports CostReport, ResourceReport, KubernetesEfficiencyReport, and FinancialCommitmentReport.'
        ),
    ] = None
    saved_filter_tokens: Annotated[
        Sequence[str] | None,
        Field(description='The tokens of the Saved Filters used in the Dashboard.'),
    ] = None
    date_bin: Annotated[
        date_bin4.DateBin | None,
        Field(description='Determines how to group costs in the Dashboard.'),
    ] = None
    date_interval: Annotated[
        date_interval3.DateInterval | None,
        Field(
            description="Determines the date range in the Dashboard. Incompatible with 'start_date' and 'end_date' parameters."
        ),
    ] = None
    start_date: Annotated[
        str | None,
        Field(
            description="The start date for the date range for costs in the Dashboard. ISO 8601 Formatted. Incompatible with 'date_interval' parameter."
        ),
    ] = None
    end_date: Annotated[
        str | None,
        Field(
            description="The end date for the date range for costs in the Dashboard. ISO 8601 Formatted. Incompatible with 'date_interval' parameter."
        ),
    ] = None
    workspace_token: Annotated[
        str | None,
        Field(
            description='The token of the Workspace to add the Dashboard to. Required if the API token is associated with multiple Workspaces.'
        ),
    ] = None
