# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence


class CreateAnomalyNotification(BaseModel):
    """
    Create an Anomaly Notification for a Cost Report.
    """
    cost_report_token: Annotated[str, Field(description='The token of the Cost Report that has the notification.')]
    threshold: Annotated[int | None, Field(description='The threshold amount that must be met for the notification to fire.')] = None
    user_tokens: Annotated[Sequence[str] | None, Field(description='The tokens of the Users that receive the notification.')] = None
    recipient_channels: Annotated[Sequence[str] | None, Field(description='The Slack/MS Teams channels that receive the notification.')] = None
