# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from collections.abc import Sequence
from . import create_access_policy_policy


class CreateAccessPolicy(BaseModel):
    """
    Create an Access Policy.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    title: Annotated[str, Field(description='The title of the AccessPolicy.')]
    policy: Annotated[create_access_policy_policy.CreateAccessPolicyPolicy, Field(description='The AccessPolicy definition as a v1 document with vantage.* VQL.', examples=[{'api_version': 'v1', 'policy': {'filter': "(vantage.provider = 'aws')"}}])]
    description: Annotated[str | None, Field(description='The description of the AccessPolicy.')] = None
    team_tokens: Annotated[Sequence[str] | None, Field(description='The tokens for Teams this AccessPolicy is assigned to.', examples=[['team_abcd1234']])] = None
