# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from collections.abc import Sequence
from typing import Annotated
from pydantic import BaseModel, Field


class CreateCostReportChartSettings(BaseModel):
    """
    Report chart settings.
    """
    x_axis_dimension: Annotated[Sequence[str] | None, Field(description="The dimension used to group or label data along the x-axis (e.g., by date, region, or service). NOTE: Only one value is allowed at this time. Defaults to ['date'].")] = None
    y_axis_dimension: Annotated[str | None, Field(description="The metric or measure displayed on the chart’s y-axis. Possible values: 'cost', 'usage'. Defaults to 'cost'.")] = None
