# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class CreateCustomProviderIntegration(BaseModel):
    """
    Create a Custom Provider Integration
    """
    name: Annotated[str, Field(description='Name of the Custom Provider Integration.')]
    description: Annotated[str | None, Field(description='Description of the Custom Provider Integration.')] = None
