# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from collections.abc import Sequence


class CreateManagedAccount(BaseModel):
    """
    Create a Managed Account.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Annotated[str, Field(description='The name of the Managed Account.')]
    contact_email: Annotated[str, Field(description='The contact email address for the Managed Account.')]
    access_credential_tokens: Annotated[Sequence[str] | None, Field(description='Access Credential (aka Integrations) tokens to assign to the Managed Account.')] = None
    billing_rule_tokens: Annotated[Sequence[str] | None, Field(description='Billing Rule tokens to assign to the Managed Account.')] = None
    email_domain: Annotated[str | None, Field(description='Email domain to associate with this Managed Account for SSO.')] = None
