# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict


class CreateVirtualTagConfigValueLabelTransform(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: str
    delimiter: str | None = None
    index: int | None = None
    template: str | None = None
