# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from pydantic import BaseModel
from . import create_dashboard_widget_settings_display_type


class CreateDashboardWidgetSettings(BaseModel):
    """
    The settings for the DashboardWidget.
    """
    display_type: create_dashboard_widget_settings_display_type.CreateDashboardWidgetSettingsDisplayType
