# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence
from . import create_budget_period


class CreateBudget(BaseModel):
    """
    Create a Budget.
    """
    name: Annotated[str, Field(description='The name of the Budget.')]
    workspace_token: Annotated[str | None, Field(description='The token of the Workspace to add the Budget to.')] = None
    cost_report_token: Annotated[str | None, Field(description='The CostReport token. Ignored for hierarchical Budgets.')] = None
    child_budget_tokens: Annotated[Sequence[str] | None, Field(description='The tokens of any child Budgets when creating a hierarchical Budget.')] = None
    periods: Annotated[Sequence[create_budget_period.CreateBudgetPeriod] | None, Field(description='The periods for the Budget. The start_at and end_at must be iso8601 formatted e.g. YYYY-MM-DD. Ignored for hierarchical Budgets.')] = None
