# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence


class CreateFolder(BaseModel):
    """
    Create a Folder for CostReports.
    """
    title: Annotated[str, Field(description='The title of the Folder.')]
    parent_folder_token: Annotated[str | None, Field(description='The token of the parent Folder.')] = None
    saved_filter_tokens: Annotated[Sequence[str] | None, Field(description='The tokens of the SavedFilters to apply to any Cost Report contained within the Folder.')] = None
    workspace_token: Annotated[str | None, Field(description="The token of the Workspace to add the Folder to. Ignored if 'parent_folder_token' is set. Required if the API token is associated with multiple Workspaces.")] = None
