# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import banking_information_attributes as banking_information_attributes_1
from . import billing_information_attributes as billing_information_attributes_1
from . import business_information_attributes as business_information_attributes_1
from . import invoice_adjustment_attributes as invoice_adjustment_attributes_1


class CreateBillingProfile(BaseModel):
    """
    Create a billing profile (MSP invoicing required).
    """

    nickname: Annotated[str, Field(description='Display name for the billing profile')]
    billing_information_attributes: Annotated[
        billing_information_attributes_1.BillingInformationAttributes | None,
        Field(description='Billing address and contact information'),
    ] = None
    business_information_attributes: Annotated[
        business_information_attributes_1.BusinessInformationAttributes | None,
        Field(description='Business information and custom fields'),
    ] = None
    banking_information_attributes: Annotated[
        banking_information_attributes_1.BankingInformationAttributes | None,
        Field(description='Banking details (MSP accounts only)'),
    ] = None
    invoice_adjustment_attributes: Annotated[
        invoice_adjustment_attributes_1.InvoiceAdjustmentAttributes | None,
        Field(description='Invoice adjustments (taxes, fees, etc.)'),
    ] = None
