# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from enum import Enum


class CreateCostReportBusinessMetricTokensWithMetadatumUnitScale(str, Enum):
    """
    Determines the scale of the BusinessMetric's values within the CostReport.
    """
    per_unit = 'per_unit'
    per_hundred = 'per_hundred'
    per_thousand = 'per_thousand'
    per_million = 'per_million'
    per_billion = 'per_billion'
