# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from . import create_access_grant_access


class CreateAccessGrant(BaseModel):
    """
    Create an Access Grant.
    """
    resource_token: Annotated[str, Field(description='The token of the resource for which you are granting access.')]
    team_token: Annotated[str, Field(description='The token of the Team you want to grant access to.')]
    access: Annotated[create_access_grant_access.CreateAccessGrantAccess | None, Field(description="The access level you want to grant. Defaults to 'allowed'.")] = None
