# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from pydantic import AwareDatetime, BaseModel


class CreateBusinessMetricForecastedValue(BaseModel):
    date: AwareDatetime
    amount: float
    label: str | None = None
