# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import Enum


class CreateNetworkFlowReportFlowDirection(str, Enum):
    """
    The flow direction of the NetworkFlowReport.
    """
    ingress = 'ingress'
    egress = 'egress'
