# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class CreateCanvas(BaseModel):
    """
    Create a Canvas.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    title: Annotated[str, Field(description='The title of the Canvas.')]
    prompt: Annotated[str, Field(description='The prompt used to generate the Canvas.')]
    workspace_token: Annotated[str | None, Field(description='The token of the Workspace to add the Canvas to. Required if the API token is associated with multiple Workspaces.')] = None
