# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from enum import Enum


class CreateNetworkFlowReportFlowWeight(str, Enum):
    """
    The dimension by which the logs in the report are sorted. Defaults to costs.
    """
    costs = 'costs'
    bytes = 'bytes'
