# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import Enum


class CreateBillingProfileInvoiceAdjustmentAttributesAdjustmentItemCalculationType(str, Enum):
    """
    How the adjustment is calculated
    """
    fixed = 'fixed'
    percentage = 'percentage'
