# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import create_cost_report_settings_aggregate_by


class CreateCostReportSettings(BaseModel):
    """
    Report settings.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    include_credits: Annotated[bool, Field(description='Report will include credits.')] = False
    include_refunds: Annotated[bool, Field(description='Report will include refunds.')] = False
    include_discounts: Annotated[bool, Field(description='Report will include discounts.')] = True
    include_tax: Annotated[bool, Field(description='Report will include tax.')] = True
    amortize: Annotated[bool, Field(description='Report will amortize.')] = True
    unallocated: Annotated[bool, Field(description='Report will show unallocated costs.')] = False
    aggregate_by: Annotated[create_cost_report_settings_aggregate_by.CreateCostReportSettingsAggregateBy, Field(description='Report will aggregate by cost, usage, or count.')] = create_cost_report_settings_aggregate_by.CreateCostReportSettingsAggregateBy.cost
    show_previous_period: Annotated[bool, Field(description='Report will show previous period cost, usage, or count comparison.')] = True
    complete_period: Annotated[bool, Field(description='Report will restrict date ranges to completed periods only.')] = False
