# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class CreateAccessPolicyPolicyApiVersion(StrEnum):
    """
    The AccessPolicy document version.
    """
    v1 = 'v1'
