# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from datetime import date
from typing import Annotated

from pydantic import BaseModel, Field

from . import aggregated_by as aggregated_by_1
from . import date_bucket2, date_interval7


class CreateKubernetesEfficiencyReport(BaseModel):
    """
    Create a KubernetesEfficiencyReport.
    """

    workspace_token: Annotated[
        str,
        Field(
            description='The Workspace in which the KubernetesEfficiencyReport will be created.'
        ),
    ]
    title: Annotated[
        str, Field(description='The title of the KubernetesEfficiencyReport.')
    ]
    filter: Annotated[
        str | None,
        Field(
            description='The filter query language to apply to the KubernetesEfficiencyReport. Additional documentation available at https://docs.vantage.sh/vql.'
        ),
    ] = None
    start_date: Annotated[
        date | None,
        Field(
            description="The start date of the KubernetesEfficiencyReport. ISO 8601 Formatted. Incompatible with 'date_interval' parameter."
        ),
    ] = None
    end_date: Annotated[
        date | None,
        Field(
            description="The end date of the KubernetesEfficiencyReport. ISO 8601 Formatted. Incompatible with 'date_interval' parameter."
        ),
    ] = None
    date_interval: Annotated[
        date_interval7.DateInterval | None,
        Field(
            description="The date interval of the KubernetesEfficiencyReport. Incompatible with 'start_date' and 'end_date' parameters. Defaults to 'this_month' if start_date and end_date are not provided."
        ),
    ] = None
    aggregated_by: Annotated[
        aggregated_by_1.AggregatedBy | None,
        Field(description='The column by which the costs are aggregated.'),
    ] = None
    date_bucket: Annotated[
        date_bucket2.DateBucket | None,
        Field(description='The date bucket of the KubernetesEfficiencyReport.'),
    ] = None
    groupings: Annotated[
        Sequence[str] | None,
        Field(
            description='Grouping values for aggregating costs on the KubernetesEfficiencyReport. Valid groupings: cluster_id, namespace, labeled, category, pod, label, label:<label_name>.'
        ),
    ] = None
