# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence
from . import create_business_metric_cloudwatch_fields, create_business_metric_cost_report_tokens_with_metadatum, create_business_metric_datadog_metric_fields, create_business_metric_forecasted_value, create_business_metric_value


class CreateBusinessMetric(BaseModel):
    """
    Create a new BusinessMetric.
    """
    title: Annotated[str, Field(description='The title of the BusinessMetrics.')]
    cost_report_tokens_with_metadata: Annotated[Sequence[create_business_metric_cost_report_tokens_with_metadatum.CreateBusinessMetricCostReportTokensWithMetadatum] | None, Field(description='The tokens for any CostReports that use the BusinessMetric, the unit scale, and label filter.')] = None
    values: Annotated[Sequence[create_business_metric_value.CreateBusinessMetricValue] | None, Field(description='The dates, amounts, and (optional) labels for the BusinessMetric.')] = None
    forecasted_values: Annotated[Sequence[create_business_metric_forecasted_value.CreateBusinessMetricForecastedValue] | None, Field(description='The dates, amounts, and (optional) labels for forecasted BusinessMetric values.')] = None
    datadog_metric_fields: Annotated[create_business_metric_datadog_metric_fields.CreateBusinessMetricDatadogMetricFields | None, Field(description='Datadog metric configuration fields')] = None
    cloudwatch_fields: Annotated[create_business_metric_cloudwatch_fields.CreateBusinessMetricCloudwatchFields | None, Field(description='Cloudwatch configuration fields.')] = None
