# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field

from . import business_metric_tokens_with_metadatum, chart_settings1
from . import chart_type as chart_type_1
from . import date_bin as date_bin_1
from . import date_interval as date_interval_1
from . import settings1


class CreateCostReport(BaseModel):
    """
    Create a CostReport.
    """

    title: Annotated[str, Field(description='The title of the CostReport.')]
    workspace_token: Annotated[
        str | None,
        Field(
            description="The token of the Workspace to add the Cost Report to. Ignored if 'folder_token' is set. Required if the API token is associated with multiple Workspaces."
        ),
    ] = None
    groupings: Annotated[
        str | None,
        Field(
            description='Grouping values for aggregating costs on the report. Valid groupings: account_id, billing_account_id, charge_type, cost_category, cost_subcategory, provider, region, resource_id, service, tagged, tag:<tag_value>. If providing multiple groupings, join as comma separated values: groupings=provider,service,region'
        ),
    ] = None
    filter: Annotated[
        str | None,
        Field(
            description='The filter query language to apply to the CostReport. Additional documentation available at https://docs.vantage.sh/vql.'
        ),
    ] = None
    saved_filter_tokens: Annotated[
        Sequence[str] | None,
        Field(description='The tokens of the SavedFilters to apply to the CostReport.'),
    ] = None
    business_metric_tokens_with_metadata: Annotated[
        Sequence[
            business_metric_tokens_with_metadatum.BusinessMetricTokensWithMetadatum
        ]
        | None,
        Field(
            description='The tokens for any BusinessMetrics to attach to the CostReport, and the unit scale.'
        ),
    ] = None
    folder_token: Annotated[
        str | None,
        Field(
            description='The token of the Folder to add the CostReport to. Determines the Workspace the report is assigned to.'
        ),
    ] = None
    settings: Annotated[
        settings1.Settings | None, Field(description='Report settings.')
    ] = None
    previous_period_start_date: Annotated[
        str | None,
        Field(
            description='The previous period start date of the CostReport. ISO 8601 Formatted.'
        ),
    ] = None
    previous_period_end_date: Annotated[
        str,
        Field(
            description='The previous period end date of the CostReport. ISO 8601 Formatted. Required when previous_period_start_date is provided.'
        ),
    ]
    start_date: Annotated[
        str | None,
        Field(
            description="The start date of the CostReport. ISO 8601 Formatted. Incompatible with 'date_interval' parameter."
        ),
    ] = None
    end_date: Annotated[
        str,
        Field(
            description="The end date of the CostReport. ISO 8601 Formatted. Required when start_date is provided. Incompatible with 'date_interval' parameter."
        ),
    ]
    date_interval: Annotated[
        date_interval_1.DateInterval | None,
        Field(
            description="The date interval of the CostReport. Incompatible with 'start_date' and 'end_date' parameters. Defaults to 'this_month' if start_date and end_date are not provided."
        ),
    ] = None
    chart_type: Annotated[
        chart_type_1.ChartType, Field(description='The chart type of the CostReport.')
    ] = 'line'
    date_bin: Annotated[
        date_bin_1.DateBin, Field(description='The date bin of the CostReport.')
    ] = 'cumulative'
    chart_settings: Annotated[
        chart_settings1.ChartSettings | None,
        Field(description='Report chart settings.'),
    ] = None
