# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class CreateBusinessMetricGcpBigqueryMetricFields(BaseModel):
    """
    GCP BigQuery metric configuration fields.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    integration_token: Annotated[str | None, Field(description='Integration token for the GCP integration from which you would like to fetch metrics.')] = None
    query_project_id: Annotated[str | None, Field(description='GCP project in which the BigQuery job should run.')] = None
    sql_query: Annotated[str | None, Field(description='BigQuery SQL query returning date, value, and optional label columns.')] = None
