# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field

from . import (
    cloudwatch_fields1,
    cost_report_tokens_with_metadatum,
    datadog_metric_fields1,
    forecasted_value,
    value,
)


class CreateBusinessMetric(BaseModel):
    """
    Create a new BusinessMetric.
    """

    title: Annotated[str, Field(description='The title of the BusinessMetrics.')]
    cost_report_tokens_with_metadata: Annotated[
        Sequence[cost_report_tokens_with_metadatum.CostReportTokensWithMetadatum]
        | None,
        Field(
            description='The tokens for any CostReports that use the BusinessMetric, the unit scale, and label filter.'
        ),
    ] = None
    values: Annotated[
        Sequence[value.Value] | None,
        Field(
            description='The dates, amounts, and (optional) labels for the BusinessMetric.'
        ),
    ] = None
    forecasted_values: Annotated[
        Sequence[forecasted_value.ForecastedValue] | None,
        Field(
            description='The dates, amounts, and (optional) labels for forecasted BusinessMetric values.'
        ),
    ] = None
    datadog_metric_fields: Annotated[
        datadog_metric_fields1.DatadogMetricFields | None,
        Field(description='Datadog metric configuration fields'),
    ] = None
    cloudwatch_fields: Annotated[
        cloudwatch_fields1.CloudwatchFields | None,
        Field(description='Cloudwatch configuration fields.'),
    ] = None
