# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class CreateInvoice(BaseModel):
    """
    Create an invoice (MSP accounts only).
    """
    billing_period_start: Annotated[str, Field(description='Start date of billing period (YYYY-MM-DD)')]
    billing_period_end: Annotated[str, Field(description='End date of billing period (YYYY-MM-DD)')]
    account_token: Annotated[str, Field(description='Token of the managed account to invoice')]
