# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import Enum


class CreateAccessGrantAccess(str, Enum):
    """
    The access level you want to grant. Defaults to 'allowed'.
    """
    denied = 'denied'
    allowed = 'allowed'
