# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence


class CreateReportNotification(BaseModel):
    """
    Create a ReportNotification.
    """
    title: Annotated[str, Field(description='The title of the ReportNotification.')]
    cost_report_token: Annotated[str, Field(description='The CostReport token.')]
    workspace_token: Annotated[str | None, Field(description='The token of the Workspace to add the ReportNotification to. Required if the API token is associated with multiple Workspaces.')] = None
    user_tokens: Annotated[Sequence[str] | None, Field(description='The Users that receive the notification.')] = None
    recipient_channels: Annotated[Sequence[str] | None, Field(description='The Slack or Microsoft Teams channels that receive the notification.')] = None
    frequency: Annotated[str, Field(description='The frequency the ReportNotification is sent. Possible values: daily, weekly, monthly.')]
    change: Annotated[str, Field(description='The type of change the ReportNotification is tracking. Possible values: percentage, dollars.')]
