# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class CreateBusinessMetricSnowflakeMetricFields(BaseModel):
    """
    Snowflake metric configuration fields.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    integration_token: Annotated[str | None, Field(description='Integration token for the Snowflake integration from which you would like to fetch metrics.')] = None
    sql_query: Annotated[str | None, Field(description='Snowflake SQL query returning date, value, and optional label columns.')] = None
