# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import date_bin2, schema


class CreateCostExport(BaseModel):
    """
    Generate a DataExport of costs.
    """

    cost_report_token: Annotated[
        str | None, Field(description='The CostReport token.')
    ] = None
    filter: Annotated[
        str | None,
        Field(
            description='The VQL filter to apply to the costs. If this is supplied you do not need cost_report_token.'
        ),
    ] = None
    workspace_token: Annotated[
        str | None,
        Field(
            description="The token of the Workspace to query costs from. Ignored if 'cost_report_token' is set. Required if the API token is associated with multiple Workspaces."
        ),
    ] = None
    start_date: Annotated[
        str | None,
        Field(
            description='First date you would like to filter costs from. ISO 8601 formatted.'
        ),
    ] = None
    end_date: Annotated[
        str | None,
        Field(
            description='Last date you would like to filter costs to. ISO 8601 formatted.'
        ),
    ] = None
    date_bin: Annotated[
        date_bin2.DateBin | None,
        Field(
            description="The date bin of the costs. Defaults to the report's default or day."
        ),
    ] = None
    schema_: Annotated[
        schema.Schema,
        Field(alias='schema', description='The schema of the data export.'),
    ] = 'vntg'
