# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from pydantic import BaseModel
from . import create_virtual_tag_config_value_cost_metric_aggregation


class CreateVirtualTagConfigValueCostMetric(BaseModel):
    filter: str
    aggregation: create_virtual_tag_config_value_cost_metric_aggregation.CreateVirtualTagConfigValueCostMetricAggregation
