# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class CreateGCPIntegration(BaseModel):
    """
    Create a GCP Integration
    """
    billing_account_id: Annotated[str, Field(description='GCP billing account ID.')]
    project_id: Annotated[str, Field(description='GCP project ID.')]
    dataset_name: Annotated[str, Field(description='BigQuery dataset name.')]
