# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict
from . import create_dashboard_widget_settings_display_type


class CreateDashboardWidgetSettings(BaseModel):
    """
    The settings for the DashboardWidget.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    display_type: create_dashboard_widget_settings_display_type.CreateDashboardWidgetSettingsDisplayType
