# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from collections.abc import Sequence
from . import create_business_metric_cloudwatch_fields_dimension


class CreateBusinessMetricCloudwatchFields(BaseModel):
    """
    Cloudwatch configuration fields.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    integration_token: Annotated[str | None, Field(description='Integration token for the account from which you would like to fetch metrics.')] = None
    stat: str | None = None
    region: str | None = None
    namespace: str | None = None
    metric_name: str | None = None
    label_dimension: str | None = None
    dimensions: Sequence[create_business_metric_cloudwatch_fields_dimension.CreateBusinessMetricCloudwatchFieldsDimension] | None = None
