# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class CreateAccessPolicyPolicyPolicy(BaseModel):
    """
    The AccessPolicy rules for this version.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    filter: Annotated[str, Field(description='Vantage Query Language (VQL) that controls which costs this AccessPolicy allows.', examples=["(vantage.provider = 'aws')"])]
