# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from datetime import date
from collections.abc import Sequence
from . import create_virtual_tag_config_collapsed_tag_key, create_virtual_tag_config_value


class CreateVirtualTagConfig(BaseModel):
    """
    Create a new VirtualTagConfig.
    """
    key: Annotated[str, Field(description='The key of the VirtualTagConfig.')]
    overridable: Annotated[bool, Field(description='Whether the VirtualTagConfig can override a provider-supplied tag on a matching Cost.')]
    backfill_until: Annotated[date | None, Field(description='The earliest month the VirtualTagConfig should be backfilled to.')] = None
    collapsed_tag_keys: Annotated[Sequence[create_virtual_tag_config_collapsed_tag_key.CreateVirtualTagConfigCollapsedTagKey] | None, Field(description='Tag keys to collapse values for.')] = None
    values: Annotated[Sequence[create_virtual_tag_config_value.CreateVirtualTagConfigValue] | None, Field(description='Values for the VirtualTagConfig, with match precedence determined by order in the list.')] = None
