# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from . import create_billing_rule_type


class CreateBillingRule(BaseModel):
    """
    Create a BillingRule.
    """
    type: Annotated[create_billing_rule_type.CreateBillingRuleType, Field(description='The type of the BillingRule. Note: the values are case insensitive.')]
    title: Annotated[str, Field(description='The title of the BillingRule.')]
    start_period: Annotated[str | None, Field(description='The start period of the BillingRule. DEPRECATED: use start_date instead.')] = None
    start_date: Annotated[str | None, Field(description='The start date of the BillingRule. ISO 8601 formatted.')] = None
    end_date: Annotated[str | None, Field(description='The end date of the BillingRule. ISO 8601 formatted.')] = None
    apply_to_all: Annotated[bool | None, Field(description='Determines if the BillingRule applies to all current and future managed accounts.')] = None
    charge_type: Annotated[str | None, Field(description='The charge type of the BillingRule. Required for Exclusion rules.')] = None
    percentage: Annotated[float | None, Field(description='The percentage of the cost shown. Required for Adjustment rules. Example value: 75.0')] = None
    service: Annotated[str | None, Field(description='The service of the BillingRule. Required for Charge and Credit rules.')] = None
    category: Annotated[str | None, Field(description='The category of the BillingRule. Required for Charge and Credit rules.')] = None
    sub_category: Annotated[str | None, Field(description='The subcategory of the BillingRule. Required for Charge and Credit rules.')] = None
    amount: Annotated[float | None, Field(description='The amount for the BillingRule. Required for Charge and Credit rules. Example value: 300')] = None
    sql_query: Annotated[str | None, Field(description='The SQL query for the BillingRule. Required for Custom rules. Example value: UPDATE costs SET costs.amount = costs.amount * 0.95')] = None
