# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class CreateAccessGrantAccess(StrEnum):
    """
    The access level you want to grant. Defaults to 'allowed'.
    """
    denied = 'denied'
    allowed = 'allowed'
