# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class CreateBusinessMetricClickhouseMetricFields(BaseModel):
    """
    ClickHouse metric configuration fields.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    integration_token: Annotated[str | None, Field(description='Integration token for the ClickHouse integration from which you would like to fetch metrics.')] = None
    query_endpoint_id: Annotated[str | None, Field(description='UUID of the ClickHouse query endpoint used to fetch metrics.')] = None
