# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import Enum


class CreateSsoConnectionForManagedAccountType(str, Enum):
    """
    The type of SSO connection. Currently supported: saml.
    """
    saml = 'saml'
