# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class CreateNetworkFlowReportFlowWeight(StrEnum):
    """
    The dimension by which the logs in the report are sorted. Defaults to costs.
    """
    costs = 'costs'
    bytes = 'bytes'
