# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import Enum


class CreateFolderType(str, Enum):
    """
    The type of the Folder.
    """
    CostFolder = 'CostFolder'
    ProviderResourceFolder = 'ProviderResourceFolder'
