# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import create_scenario_model_period


class CreateScenarioModel(BaseModel):
    """
    Create a ScenarioModel.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    title: str
    priority: int | None = None
    provider: str | None = None
    service: str | None = None
    workspace_token: str | None = None
    periods: Annotated[Sequence[create_scenario_model_period.CreateScenarioModelPeriod] | None, Field(description='The periods for the ScenarioModel.')] = None
