# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class CreateTwilioIntegration(BaseModel):
    """
    Create a Twilio Integration
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    api_key: Annotated[str, Field(description='Twilio API key SID.')]
    api_secret: Annotated[str, Field(description='Twilio API key secret.')]
    account_sid: Annotated[str, Field(description='Twilio account SID.')]
    friendly_account_name: Annotated[str, Field(description='Name for this Twilio account in Vantage.')]
    description: Annotated[str, Field(description='Description of the integration.')]
    is_oauth: Annotated[bool | None, Field(description='When true, api_key and api_secret are an OAuth client id and secret.')] = None
