# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from enum import Enum


class CreateBillingProfileInvoiceAdjustmentAttributesAdjustmentItemCalculationType(str, Enum):
    """
    How the adjustment is calculated
    """
    fixed = 'fixed'
    percentage = 'percentage'
