# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from enum import Enum


class CreateKubernetesEfficiencyReportAggregatedBy(str, Enum):
    """
    The column by which the costs are aggregated.
    """
    idle_cost = 'idle_cost'
    amount = 'amount'
    cost_efficiency = 'cost_efficiency'
