# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class CreateCostExportSchema(StrEnum):
    """
    The schema of the data export.
    """
    vntg = 'vntg'
    focus = 'focus'
    comparison = 'comparison'
