# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from enum import Enum


class CreateFinancialCommitmentReportDateBucket(str, Enum):
    """
    The date bucket of the FinancialCommitmentReport.
    """
    hour = 'hour'
    day = 'day'
    week = 'week'
    month = 'month'
    quarter = 'quarter'
