# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from enum import Enum


class CreateWorkspaceExchangeRateDate(str, Enum):
    """
    The date to use for currency conversion.
    """
    daily_rate = 'daily_rate'
    end_of_billing_period_rate = 'end_of_billing_period_rate'
