# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class DashboardWidgetGridLayout(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    x: Annotated[int, Field(description='The zero-based horizontal position in the 12-column grid.')]
    y: Annotated[int, Field(description='The zero-based vertical position in the grid.')]
    w: Annotated[int, Field(description='The widget width in grid columns.')]
    h: Annotated[int, Field(description='The widget height in grid rows.')]
