# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import dashboard_widget_settings


class DashboardWidget(BaseModel):
    widgetable_token: Annotated[str, Field(examples=['rprt_a12b3c'])]
    title: Annotated[
        str, Field(description='The title of the Widget.', examples=['My Widget'])
    ]
    settings: dashboard_widget_settings.DashboardWidgetSettings
