# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence
from . import dashboard_date_bin, dashboard_date_interval, dashboard_widget


class Dashboard(BaseModel):
    """
    Dashboard model
    """
    token: Annotated[str, Field(examples=['dshbrd_abcd1234567890'])]
    title: Annotated[str, Field(description='The title of the Dashboard.', examples=['AWS Dashboard'])]
    widgets: Sequence[dashboard_widget.DashboardWidget]
    saved_filter_tokens: Annotated[Sequence[str], Field(description='The tokens of the Saved Filters used in the Dashboard.')]
    date_bin: Annotated[dashboard_date_bin.DashboardDateBin | None, Field(description='Determines how to group costs in the Dashboard.')]
    date_interval: Annotated[dashboard_date_interval.DashboardDateInterval | None, Field(description="Determines the date range for Reports in the Dashboard. Guaranteed to be set to 'custom' if 'start_date' and 'end_date' are set.")]
    start_date: Annotated[str | None, Field(description="The start date for the date range for Reports in the Dashboard. ISO 8601 Formatted. Overwrites 'date_interval' if set.", examples=['2023-08-04'])] = None
    end_date: Annotated[str | None, Field(description="The end date for the date range for Reports in the Dashboard. ISO 8601 Formatted. Overwrites 'date_interval' if set.", examples=['2023-09-04'])] = None
    created_at: Annotated[str, Field(description='The date and time, in UTC, the Dashboard was created. ISO 8601 Formatted.', examples=['2023-08-04T00:00:00Z'])]
    updated_at: Annotated[str, Field(description='The date and time, in UTC, the Dashboard was created. ISO 8601 Formatted.', examples=['2023-08-04T00:00:00Z'])]
    workspace_token: Annotated[str, Field(description='The token for the Workspace the Dashboard is a part of.', examples=['wrkspc_abcd1234567890'])]
