# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class DashboardNotificationFrequency(StrEnum):
    """
    The frequency the DashboardNotification is sent.
    """
    daily = 'daily'
    weekly = 'weekly'
    monthly = 'monthly'
