# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from pydantic import BaseModel
from . import dashboard_widget_settings_display_type


class DashboardWidgetSettings(BaseModel):
    display_type: dashboard_widget_settings_display_type.DashboardWidgetSettingsDisplayType
