# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict
from . import dashboard_widget_settings_display_type


class DashboardWidgetSettings(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    display_type: dashboard_widget_settings_display_type.DashboardWidgetSettingsDisplayType
