# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel
from . import dashboard, links as links_1


class Dashboards(BaseModel):
    """
    Dashboards model
    """
    links: links_1.Links | None = None
    dashboards: Sequence[dashboard.Dashboard]
