# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel, ConfigDict
from . import dashboard_notification, links as links_1


class DashboardNotifications(BaseModel):
    """
    DashboardNotifications model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    links: links_1.Links | None = None
    dashboard_notifications: Sequence[dashboard_notification.DashboardNotification]
