# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from . import data_export_manifest


class DataExport(BaseModel):
    """
    DataExport model
    """
    token: Annotated[str, Field(examples=['dta_xprt_abcd1234567890'])]
    status: Annotated[str, Field(examples=['pending'])]
    created_at: Annotated[str, Field(examples=['2025-03-20T12:00:00Z'])]
    export_type: Annotated[str, Field(examples=['cost_report'])]
    manifest: data_export_manifest.DataExportManifest
    attributes: str
