# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from typing import Annotated
from pydantic import BaseModel, Field


class DataExportManifest(BaseModel):
    files: Sequence[str]
    completed_at: Annotated[str | None, Field(examples=['2025-03-20T12:00:00Z'])]
    valid_until: Annotated[str | None, Field(examples=['2025-03-20T12:00:00Z'])]
