# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class DatadogMetricFields(BaseModel):
    query: Annotated[
        str,
        Field(
            description='The query used to import Datadog metrics.',
            examples=[
                'sum:aws.applicationelb.request_count{region:us-east-1}.rollup(avg,daily)'
            ],
        ),
    ]
