# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class DataExportManifest(BaseModel):
    files: Annotated[str, Field(examples=[''])]
    completed_at: Annotated[str, Field(examples=['2025-03-20T12:00:00Z'])]
    valid_until: Annotated[str, Field(examples=['2025-03-20T12:00:00Z'])]
