# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from enum import Enum


class DateBin(str, Enum):
    """
    The date bin of the CostReport.
    """

    cumulative = 'cumulative'
    day = 'day'
    week = 'week'
    month = 'month'
    quarter = 'quarter'
