# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from enum import Enum


class DateInterval(str, Enum):
    """
    The date interval of the FinancialCommitmentReport. Unless 'custom' is used, this is incompatible with 'start_date' and 'end_date' parameters. Defaults to 'last_3_months'.
    """

    this_month = 'this_month'
    last_7_days = 'last_7_days'
    last_30_days = 'last_30_days'
    last_month = 'last_month'
    last_3_months = 'last_3_months'
    last_6_months = 'last_6_months'
    custom = 'custom'
    last_12_months = 'last_12_months'
    last_24_months = 'last_24_months'
    last_36_months = 'last_36_months'
    year_to_date = 'year_to_date'
    last_3_days = 'last_3_days'
    last_14_days = 'last_14_days'
