# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from enum import Enum


class DateInterval(str, Enum):
    """
    Determines the date range for Reports in the Dashboard. Guaranteed to be set to 'custom' if 'start_date' and 'end_date' are set.
    """

    this_month = 'this_month'
    last_7_days = 'last_7_days'
    last_30_days = 'last_30_days'
    last_month = 'last_month'
    last_3_months = 'last_3_months'
    last_6_months = 'last_6_months'
    custom = 'custom'
    last_12_months = 'last_12_months'
    last_24_months = 'last_24_months'
    last_36_months = 'last_36_months'
    next_month = 'next_month'
    next_3_months = 'next_3_months'
    next_6_months = 'next_6_months'
    next_12_months = 'next_12_months'
    year_to_date = 'year_to_date'
    last_3_days = 'last_3_days'
    last_14_days = 'last_14_days'
