# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import default_forecast_kind


class DefaultForecast(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    kind: Annotated[default_forecast_kind.DefaultForecastKind, Field(description='The default forecast selection kind.')]
    report_forecast_token: Annotated[str | None, Field(description='The token for the report forecast selected as the default.')] = None
