# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class DownloadInvoice(BaseModel):
    """
    DownloadInvoice model
    """
    download_url: Annotated[str, Field(description='The URL to download the invoice file.', examples=['https://example.com/invoice.pdf'])]
