# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from . import download_invoice_file_type


class DownloadInvoice(BaseModel):
    """
    Download invoice file (PDF or CSV).
    """
    file_type: Annotated[download_invoice_file_type.DownloadInvoiceFileType, Field(description='Type of file to download (pdf or csv)')]
