# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import file_type as file_type_1


class DownloadInvoice(BaseModel):
    """
    Download invoice file (PDF or CSV).
    """

    file_type: Annotated[
        file_type_1.FileType, Field(description='Type of file to download (pdf or csv)')
    ]
