# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class EnrichmentStatistic(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: str
    provider: Annotated[str, Field(description='The key of the provider whose costs were enriched.', examples=['aws'])]
    account_identifier: Annotated[str, Field(description='The account identifier for the integration whose costs were enriched.')]
    status: str
    status_detail: Annotated[str | None, Field(...)]
    status_message: Annotated[str | None, Field(...)]
    start_date: Annotated[str | None, Field(...)]
    end_date: Annotated[str | None, Field(...)]
    ingested_at: Annotated[str | None, Field(description='The date and time when Vantage last enriched this billing period.')]
    log_scan_acceptance_rate: Annotated[float | None, Field(description='The share of log lines that Vantage read and indexed.')]
    log_record_match_rate: Annotated[float | None, Field(description='The share of indexed log records that matched cost data.')]
    bill_match_rate: Annotated[float | None, Field(description='The share of cost rows that received logged usage.')]
    ambiguous_sibling_rows: Annotated[int, Field(description='The number of rows that Vantage could not assign to one integration.')]
    tokens_kept_rate: Annotated[float | None, Field(description='The share of indexed tokens that Vantage attached to a cost row.')]
