# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import enrichment_sources_enrichment_source_token_statistics_get_parameters_query_provider


class EnrichmentSourcesEnrichmentSourceTokenStatisticsGetParametersQuery(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    page: int = 1
    limit: Annotated[int, Field(ge=1, le=1000)] = 50
    provider: enrichment_sources_enrichment_source_token_statistics_get_parameters_query_provider.EnrichmentSourcesEnrichmentSourceTokenStatisticsGetParametersQueryProvider | None = None
