# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel, ConfigDict
from . import exchange_rate, links as links_1


class ExchangeRates(BaseModel):
    """
    ExchangeRates model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    links: links_1.Links | None = None
    exchange_rates: Sequence[exchange_rate.ExchangeRate]
