# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from enum import Enum


class ExchangeRateDate(str, Enum):
    """
    The date to use for currency conversion.
    """

    daily_rate = 'daily_rate'
    end_of_billing_period_rate = 'end_of_billing_period_rate'
