# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class ExchangeRatesCsvPostRequest(BaseModel):
    csv: Annotated[bytes, Field(description='CSV file containing exchange rates. Format: base_currency_code, currency_code, rate, date (YYYY-MM-DD)')]
