# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict


class ExchangeRate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    base_currency_code: str
    currency_code: str
    rate: str
    effective_date: str
    updated_at: str
