# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence

from pydantic import BaseModel

from . import financial_commitment_report
from . import links as links_1


class FinancialCommitmentReports(BaseModel):
    """
    FinancialCommitmentReports model
    """

    links: links_1.Links | None = None
    financial_commitment_reports: Sequence[
        financial_commitment_report.FinancialCommitmentReport
    ]
