# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class FinancialCommitmentReportCostTag(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    key: Annotated[str, Field(description='The tag key.', examples=['Name'])]
    value: Annotated[str | None, Field(description='The tag value. Null when the cost is not tagged with this key.', examples=['production'])]
