# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class FinancialCommitmentReport(BaseModel):
    """
    FinancialCommitmentReport model
    """
    token: str
    title: Annotated[str, Field(description='The title of the FinancialCommitmentReport.', examples=['Acme123 Financial Commitment Report'])]
    default: Annotated[bool, Field(description='Indicates whether the FinancialCommitmentReport is the default report.')]
    created_at: Annotated[str, Field(description='The date and time, in UTC, the report was created. ISO 8601 Formatted.', examples=['2024-03-19T00:00:00Z'])]
    workspace_token: Annotated[str, Field(description='The token for the Workspace the FinancialCommitmentReport is a part of.')]
    user_token: Annotated[str | None, Field(description='The token for the User who created this FinancialCommitmentReport.')] = None
    start_date: Annotated[str | None, Field(description='The start date for the FinancialCommitmentReport. Only set for custom date ranges. ISO 8601 Formatted.', examples=['2024-03-01'])]
    end_date: Annotated[str | None, Field(description='The end date for the FinancialCommitmentReport. Only set for custom date ranges. ISO 8601 Formatted.', examples=['2024-03-20'])]
    date_interval: Annotated[str | None, Field(description='The date range for the FinancialCommitmentReport. Only present if a custom date range is not specified.', examples=['last_month'])]
    date_bucket: Annotated[str, Field(description='How costs are grouped and displayed in the FinancialCommitmentReport. Possible values: day, week, month.', examples=['month'])]
    groupings: Annotated[str | None, Field(description='The grouping aggregations applied to the filtered data.', examples=['cost_type, tag:account'])]
    on_demand_costs_scope: Annotated[str, Field(description='The scope for the costs. Possible values: discountable, all.', examples=['discountable'])]
    filter: Annotated[str | None, Field(description='The filter applied to the FinancialCommitmentReport. Additional documentation available at https://docs.vantage.sh/vql.')]
