# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from datetime import date as date_aliased
from collections.abc import Sequence
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import financial_commitment_reports_financial_commitment_report_token_costs_get_parameters_query_date_bin, financial_commitment_reports_financial_commitment_report_token_costs_get_parameters_query_on_demand_costs_scope, financial_commitment_reports_financial_commitment_report_token_costs_get_parameters_query_order


class FinancialCommitmentReportsFinancialCommitmentReportTokenCostsGetParametersQuery(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    start_date: date_aliased | None = None
    end_date: date_aliased | None = None
    date_bin: financial_commitment_reports_financial_commitment_report_token_costs_get_parameters_query_date_bin.FinancialCommitmentReportsFinancialCommitmentReportTokenCostsGetParametersQueryDateBin | None = None
    groupings: Sequence[str] | None = None
    filter: str | None = None
    on_demand_costs_scope: financial_commitment_reports_financial_commitment_report_token_costs_get_parameters_query_on_demand_costs_scope.FinancialCommitmentReportsFinancialCommitmentReportTokenCostsGetParametersQueryOnDemandCostsScope | None = None
    order: financial_commitment_reports_financial_commitment_report_token_costs_get_parameters_query_order.FinancialCommitmentReportsFinancialCommitmentReportTokenCostsGetParametersQueryOrder = financial_commitment_reports_financial_commitment_report_token_costs_get_parameters_query_order.FinancialCommitmentReportsFinancialCommitmentReportTokenCostsGetParametersQueryOrder.desc
    limit: Annotated[int, Field(ge=1, le=5000)] = 2500
    page: int = 1
