# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel
from . import financial_commitment, links as links_1


class FinancialCommitments(BaseModel):
    """
    FinancialCommitments model
    """
    links: links_1.Links | None = None
    financial_commitments: Sequence[financial_commitment.FinancialCommitment]
