# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from collections.abc import Sequence
from . import financial_commitment_report_cost_tag


class FinancialCommitmentReportCost(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    accrued_at: Annotated[str, Field(description='The date the cost was accrued. ISO 8601 Formatted.', examples=['2024-03-01T00:00:00Z'])]
    amount: Annotated[str, Field(description='The net (discounted) cost amount.', examples=['100.00'])]
    gross_amount: Annotated[str, Field(description='The gross cost amount before discounts.', examples=['150.00'])]
    on_demand_amount: Annotated[str, Field(description='The on-demand usage cost amount.', examples=['50.00'])]
    covered_gross_amount: Annotated[str, Field(description='The gross amount of costs covered by commitments.', examples=['100.00'])]
    currency: Annotated[str, Field(description='The currency of the cost.', examples=['USD'])]
    cost_type: Annotated[str | None, Field(description='The type of cost.', examples=['SavingsPlanCoveredUsage'])] = None
    commitment_type: Annotated[str | None, Field(description='The type of financial commitment.', examples=['savings_plan'])] = None
    commitment_id: Annotated[str | None, Field(description='The identifier of the financial commitment.', examples=['sp-1234567890abcdef0'])] = None
    service: Annotated[str | None, Field(description='The service which incurred the cost.', examples=['Amazon Elastic Compute Cloud - Compute'])] = None
    resource_account_id: Annotated[str | None, Field(description='The resource account ID which incurred the cost.', examples=['123456789012'])] = None
    provider_account_id: Annotated[str | None, Field(description='The billing account ID which incurred the cost.', examples=['123456789012'])] = None
    region: Annotated[str | None, Field(description='The region which incurred the cost.', examples=['us-east-1'])] = None
    cost_category: Annotated[str | None, Field(description='The category for the cost.', examples=['Data Transfer'])] = None
    cost_sub_category: Annotated[str | None, Field(description='The subcategory for the cost.', examples=['DataTransfer-Regional-Bytes'])] = None
    instance_type: Annotated[str | None, Field(description='The instance type which incurred the cost.', examples=['m5.xlarge'])] = None
    tags: Annotated[Sequence[financial_commitment_report_cost_tag.FinancialCommitmentReportCostTag] | None, Field(description='The tag key/value pairs attached to the cost that was incurred.')] = None
