# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel, ConfigDict
from . import cost_partial, financial_commitment_report_cost, links as links_1


class FinancialCommitmentReportCosts(BaseModel):
    """
    FinancialCommitmentReportCosts model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    links: links_1.Links | None = None
    total_amount: cost_partial.CostPartial
    total_gross_amount: cost_partial.CostPartial
    costs: Sequence[financial_commitment_report_cost.FinancialCommitmentReportCost]
