# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel
from . import folder, links as links_1


class Folders(BaseModel):
    """
    Folders model
    """
    links: links_1.Links | None = None
    folders: Sequence[folder.Folder]
