# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence


class Folder(BaseModel):
    """
    Folder model
    """
    token: str
    title: Annotated[str | None, Field(description='The title of the Folder.', examples=['Platform Team Reports'])]
    parent_folder_token: Annotated[str | None, Field(description='The token for the parent Folder, if any.')] = None
    saved_filter_tokens: Annotated[Sequence[str], Field(description='The tokens for the SavedFilters assigned to the Folder.')]
    created_at: Annotated[str, Field(description='The date and time, in UTC, the Folder was created. ISO 8601 Formatted.', examples=['2023-08-04T00:00:00Z'])]
    updated_at: Annotated[str, Field(description='The date and time, in UTC, the Folder was last updated at. ISO 8601 Formatted.', examples=['2023-08-04T00:00:00Z'])]
    workspace_token: Annotated[str, Field(description='The token for the Workspace the Folder is a part of.')]
