# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import Enum


class FoldersGetParametersQueryType(str, Enum):
    CostFolder = 'CostFolder'
    ProviderResourceFolder = 'ProviderResourceFolder'
