# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import forecasted_cost, links as links_1


class ForecastedCosts(BaseModel):
    """
    ForecastedCosts model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    links: links_1.Links | None = None
    forecasted_costs: Sequence[forecasted_cost.ForecastedCost]
    currency: Annotated[str | None, Field(description='The currency of the forecasted costs.', examples=['USD'])]
