# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field

from . import forecasted_cost
from . import links as links_1


class ForecastedCosts(BaseModel):
    """
    ForecastedCosts model
    """

    links: links_1.Links | None = None
    forecasted_costs: Sequence[forecasted_cost.ForecastedCost]
    currency: Annotated[
        str | None,
        Field(description='The currency of the forecasted costs.', examples=['USD']),
    ]
