# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from enum import Enum


class Grouping(str, Enum):
    account_id = 'account_id'
    az_id = 'az_id'
    dstaddr = 'dstaddr'
    dsthostname = 'dsthostname'
    flow_direction = 'flow_direction'
    interface_id = 'interface_id'
    instance_id = 'instance_id'
    peer_resource_uuid = 'peer_resource_uuid'
    peer_account_id = 'peer_account_id'
    peer_vpc_id = 'peer_vpc_id'
    peer_region = 'peer_region'
    peer_az_id = 'peer_az_id'
    peer_subnet_id = 'peer_subnet_id'
    peer_interface_id = 'peer_interface_id'
    peer_instance_id = 'peer_instance_id'
    region = 'region'
    resource_uuid = 'resource_uuid'
    srcaddr = 'srcaddr'
    srchostname = 'srchostname'
    subnet_id = 'subnet_id'
    traffic_category = 'traffic_category'
    traffic_path = 'traffic_path'
    vpc_id = 'vpc_id'
