# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from enum import Enum


class ImportType(str, Enum):
    """
    The type of import for the BusinessMetric.
    """

    datadog_metrics = 'datadog_metrics'
    cloudwatch = 'cloudwatch'
    csv = 'csv'
