# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence
from . import integration_status


class Integration(BaseModel):
    """
    Integration model
    """
    token: str
    provider: Annotated[str, Field(description='The name of the Integration.', examples=['AWS'])]
    account_identifier: Annotated[str | None, Field(description='The account identifier. For GCP this is the billing Account ID, for Azure this is the account ID', examples=['011389-EF4C3E-3ED7AE'])]
    status: Annotated[integration_status.IntegrationStatus, Field(description="The status of the Integration. Can be 'connected', 'error', 'pending', 'importing', 'imported', or 'disconnected'.", examples=['imported'])]
    last_updated: Annotated[str | None, Field(description='The date and time, in UTC, when the Integration was last updated. ISO 8601 Formatted.', examples=['2023-08-04T00:00:00Z'])] = None
    workspace_tokens: Annotated[Sequence[str], Field(description='The tokens for any Workspaces that the account belongs to.')]
    created_at: Annotated[str, Field(description='The date and time, in UTC, the Integration was created. ISO 8601 Formatted.', examples=['2023-08-04T00:00:00Z'])]
