# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class IntegrationsIntegrationTokenCostsCsvPostRequest(BaseModel):
    csv: Annotated[bytes, Field(description='CSV file containing custom costs')]
    auto_transform: Annotated[bool, Field(description='Attempt to automatically transform the CSV file to match the FOCUS format.')] = False
