# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import provider4


class IntegrationsGetParametersQuery(BaseModel):
    provider: provider4.Provider | None = None
    account_identifier: str | None = None
    page: int | None = None
    limit: int | None = None
