# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from pydantic import BaseModel
from . import integrations_get_parameters_query_provider


class IntegrationsGetParametersQuery(BaseModel):
    provider: integrations_get_parameters_query_provider.IntegrationsGetParametersQueryProvider | None = None
    account_identifier: str | None = None
    page: int | None = None
    limit: int | None = None
