# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field

from . import adjustment_item1


class InvoiceAdjustmentAttributes(BaseModel):
    """
    Invoice adjustments (taxes, fees, etc.)
    """

    token: str | None = None
    adjustment_items: Annotated[
        Sequence[adjustment_item1.AdjustmentItem] | None,
        Field(description='Array of adjustment items'),
    ] = None
