# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class Invoice(BaseModel):
    """
    Invoice model
    """

    token: str
    invoice_number: Annotated[
        str, Field(description='Sequential invoice number for the MSP account')
    ]
    total: Annotated[
        str | None, Field(description='Total amount for the invoice period')
    ]
    billing_period_start: Annotated[
        str, Field(description='Start date of the billing period. ISO 8601 formatted.')
    ]
    billing_period_end: Annotated[
        str, Field(description='End date of the billing period. ISO 8601 formatted.')
    ]
    status: Annotated[str, Field(description='Current status of the invoice')]
    created_at: Annotated[
        str,
        Field(
            description='The date and time, in UTC, the invoice was created. ISO 8601 formatted.'
        ),
    ]
    updated_at: Annotated[
        str,
        Field(
            description='The date and time, in UTC, the invoice was last updated. ISO 8601 formatted.'
        ),
    ]
    account_token: Annotated[
        str, Field(description='Token of the managed account this invoice belongs to')
    ]
    account_name: Annotated[
        str, Field(description='Name of the managed account this invoice belongs to')
    ]
    msp_account_token: Annotated[
        str, Field(description='Token of the MSP account that owns this invoice')
    ]
