# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class KubernetesEfficiencyReportsDataExportsPostParametersQueryGroupings(StrEnum):
    cluster_id = 'cluster_id'
    namespace = 'namespace'
    region = 'region'
    labeled = 'labeled'
    category = 'category'
    pod = 'pod'
