# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class KubernetesEfficiencyReportCostLabel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    key: Annotated[str, Field(description='The Kubernetes label key.', examples=['app'])]
    value: Annotated[str | None, Field(description='The Kubernetes label value. Null when the label key is not present.', examples=['payments'])]
