# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from collections.abc import Sequence
from . import cost_partial, kubernetes_efficiency_report_cost, links as links_1


class KubernetesEfficiencyReportCosts(BaseModel):
    """
    KubernetesEfficiencyReportCosts model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    links: links_1.Links | None = None
    total_amount: cost_partial.CostPartial
    total_idle_cost: cost_partial.CostPartial
    total_cost_efficiency: Annotated[str, Field(description='The cost efficiency ratio for the complete filtered result.', examples=['0.66666666666666666667'])]
    costs: Sequence[kubernetes_efficiency_report_cost.KubernetesEfficiencyReportCost]
