# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class KubernetesEfficiencyReport(BaseModel):
    """
    KubernetesEfficiencyReport model
    """
    token: str
    title: Annotated[str, Field(description='The title of the KubernetesEfficiencyReport.', examples=['Acme123 Kubernetes Efficiency Metrics'])]
    default: Annotated[bool, Field(description='Indicates whether the KubernetesEfficiencyReport is the default report.')]
    created_at: Annotated[str, Field(description='The date and time, in UTC, the report was created. ISO 8601 Formatted.', examples=['2024-03-19T00:00:00Z'])]
    workspace_token: Annotated[str, Field(description='The token for the Workspace the KubernetesEfficiencyReport is a part of.')]
    user_token: Annotated[str | None, Field(description='The token for the User who created this KubernetesEfficiencyReport.')] = None
    start_date: Annotated[str | None, Field(description='The start date for the KubernetesEfficiencyReport. Only set for custom date ranges. ISO 8601 Formatted.', examples=['2024-03-01'])]
    end_date: Annotated[str | None, Field(description='The end date for the KubernetesEfficiencyReport. Only set for custom date ranges. ISO 8601 Formatted.', examples=['2024-03-20'])]
    date_interval: Annotated[str | None, Field(description='The date range for the KubernetesEfficiencyReport. Only present if a custom date range is not specified.', examples=['last_month'])]
    date_bucket: Annotated[str, Field(description='How costs are grouped and displayed in the KubernetesEfficiencyReport. Possible values: day, week, month.', examples=['month'])]
    aggregated_by: Annotated[str, Field(description='How costs are aggregated by. Possible values: idle_cost, amount, cost_efficiency.')]
    groupings: Annotated[str | None, Field(description='Grouping values for aggregating costs on the KubernetesEfficiencyReport. Valid groupings: cluster_id, namespace, labeled, category, pod, label, label:<label_name>.', examples=['cluster_id, namespace'])]
    filter: Annotated[str | None, Field(description='The filter applied to the KubernetesEfficiencyReport. Additional documentation available at https://docs.vantage.sh/vql.')]
