# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel


class KubernetesEfficiencyReportsDataExportsPostParametersQuery(BaseModel):
    groupings: Sequence[str] | None = None
