# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from collections.abc import Sequence
from . import kubernetes_efficiency_report_cost_label


class KubernetesEfficiencyReportCost(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    accrued_at: Annotated[str, Field(description='The date bucket for the cost. YYYY-MM-DD formatted.', examples=['2026-09-01'])]
    amount: Annotated[str, Field(description='The total cost amount for the row.', examples=['120'])]
    idle_cost: Annotated[str, Field(description='The idle cost amount for the row.', examples=['40'])]
    cost_efficiency: Annotated[str, Field(description='The cost efficiency ratio for the row, expressed from 0 to 1 under ordinary inputs.', examples=['0.66666666666666666667'])]
    currency: Annotated[str, Field(description='The ISO 4217 currency code for the costs.', examples=['USD'])]
    cluster_id: Annotated[str | None, Field(description='The cluster_id grouping value.')] = None
    namespace: Annotated[str | None, Field(description='The namespace grouping value.')] = None
    region: Annotated[str | None, Field(description='The region grouping value.')] = None
    category: Annotated[str | None, Field(description='The category grouping value.')] = None
    pod: Annotated[str | None, Field(description='The pod grouping value.')] = None
    labeled: Annotated[bool, Field(description='Whether the aggregated Kubernetes records contain any labels.')] = None
    labels: Annotated[Sequence[kubernetes_efficiency_report_cost_label.KubernetesEfficiencyReportCostLabel] | None, Field(description='The requested Kubernetes label grouping values.')] = None
