# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel, ConfigDict
from . import kubernetes_efficiency_report, links as links_1


class KubernetesEfficiencyReports(BaseModel):
    """
    KubernetesEfficiencyReports model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    links: links_1.Links | None = None
    kubernetes_efficiency_reports: Sequence[kubernetes_efficiency_report.KubernetesEfficiencyReport]
