# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel
from . import kubernetes_efficiency_report, links as links_1


class KubernetesEfficiencyReports(BaseModel):
    """
    KubernetesEfficiencyReports model
    """
    links: links_1.Links | None = None
    kubernetes_efficiency_reports: Sequence[kubernetes_efficiency_report.KubernetesEfficiencyReport]
