# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class Links(BaseModel):
    self: Annotated[
        str | None, Field(description='The URL of the current page of results.')
    ] = None
    first: Annotated[
        str | None, Field(description='The URL of the first page of results.')
    ] = None
    next: Annotated[
        str | None,
        Field(description='The URL of the next page of results, if one exists.'),
    ] = None
    last: Annotated[
        str | None,
        Field(description='The URL of the last page of results, if one exists.'),
    ] = None
    prev: Annotated[
        str | None,
        Field(description='The URL of the previous page of results, if one exists.'),
    ] = None
