# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel
from . import links as links_1, managed_account


class ManagedAccounts(BaseModel):
    """
    ManagedAccounts model
    """
    links: links_1.Links | None = None
    managed_accounts: Sequence[managed_account.ManagedAccount]
