# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence

from pydantic import BaseModel

from . import links as links_1
from . import managed_account


class ManagedAccounts(BaseModel):
    """
    ManagedAccounts model
    """

    links: links_1.Links | None = None
    managed_accounts: Sequence[managed_account.ManagedAccount]
