# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field

from . import billing_information, business_information


class ManagedAccount(BaseModel):
    """
    ManagedAccount model
    """

    token: str
    name: str
    contact_email: str
    parent_account_token: Annotated[
        str, Field(description='The token for the parent Account.')
    ]
    access_credential_tokens: Annotated[
        Sequence[str],
        Field(
            description='The tokens for the Access Credentials assigned to the Managed Account.'
        ),
    ]
    billing_rule_tokens: Annotated[
        Sequence[str],
        Field(
            description='The tokens for the Billing Rules assigned to the Managed Account.'
        ),
    ]
    email_domain: Annotated[
        str | None,
        Field(description='Email domain associated with this Managed Account for SSO.'),
    ] = None
    msp_billing_profile_token: Annotated[
        str | None,
        Field(
            description='Token of the MSP billing profile used for this managed account (MSP invoicing accounts only)'
        ),
    ] = None
    billing_information_attributes: billing_information.BillingInformation | None = None
    business_information_attributes: business_information.BusinessInformation | None = (
        None
    )
