# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence

from pydantic import BaseModel

from . import bearer_token as bearer_token_1
from . import workspace


class Me(BaseModel):
    """
    Me model
    """

    default_workspace_token: str
    workspaces: Sequence[workspace.Workspace]
    bearer_token: bearer_token_1.BearerToken
