# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated, Any
from pydantic import BaseModel, ConfigDict, Field
from collections.abc import Mapping, Sequence
from . import links as links_1, network_flow_log


class NetworkFlowLogs(BaseModel):
    """
    NetworkFlowLogs model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    links: links_1.Links | None = None
    flow_weight: Annotated[str, Field(description='The dimension used to order the aggregated rows.')]
    sampling: Annotated[Mapping[str, Any], Field(description='Sampling metadata for the selected data.')]
    network_flow_logs: Sequence[network_flow_log.NetworkFlowLog]
