# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class NetworkFlowReport(BaseModel):
    """
    NetworkFlowReport model
    """

    token: str
    title: Annotated[
        str,
        Field(
            description='The title of the NetworkFlowReport.',
            examples=['Public Traffic Destinations'],
        ),
    ]
    default: Annotated[
        bool,
        Field(
            description='Indicates whether the NetworkFlowReport is the default report.'
        ),
    ]
    created_at: Annotated[
        str,
        Field(
            description='The date and time, in UTC, the report was created. ISO 8601 Formatted.',
            examples=['2024-03-19T00:00:00Z'],
        ),
    ]
    workspace_token: Annotated[
        str,
        Field(
            description='The token for the Workspace the NetworkFlowReport is a part of.'
        ),
    ]
    created_by_token: Annotated[
        str | None,
        Field(
            description='The token for the User or Team that created this NetworkFlowReport.'
        ),
    ] = None
    start_date: Annotated[
        str | None,
        Field(
            description='The start date for the NetworkFlowReport. Only set for custom date ranges. ISO 8601 Formatted.',
            examples=['2024-03-01'],
        ),
    ]
    end_date: Annotated[
        str | None,
        Field(
            description='The end date for the NetworkFlowReport. Only set for custom date ranges. ISO 8601 Formatted.',
            examples=['2024-03-20'],
        ),
    ]
    date_interval: Annotated[
        str | None,
        Field(
            description='The date range for the NetworkFlowReport. Only present if a custom date range is not specified.',
            examples=['last_month'],
        ),
    ]
    groupings: Annotated[
        str | None,
        Field(
            description='The grouping aggregations applied to the filtered data.',
            examples=['cost_type, tag:account'],
        ),
    ]
    flow_direction: Annotated[
        str | None,
        Field(
            description='The flow weight of the NetworkFlowReport. Possible values: costs, bytes.',
            examples=['ingress'],
        ),
    ]
    flow_weight: Annotated[
        str,
        Field(
            description='The flow weight of the NetworkFlowReport. Possible values: costs, bytes.',
            examples=['costs'],
        ),
    ]
    filter: Annotated[
        str | None,
        Field(
            description='The filter applied to the NetworkFlowReport. Additional documentation available at https://docs.vantage.sh/vql.'
        ),
    ]
