# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from datetime import date
from typing import Annotated

from pydantic import BaseModel, Field


class Period(BaseModel):
    start_at: Annotated[date, Field(description='The start date of the period.')]
    end_at: Annotated[date | None, Field(description='The end date of the period.')] = (
        None
    )
    amount: Annotated[float, Field(description='The amount of the period.')]
