# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class PeriodCadence(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    starts_at: Annotated[str | None, Field(description='The anchor date for budget period intervals. ISO 8601 date (YYYY-MM-DD).', examples=['2026-01-01'])] = None
    interval_count: Annotated[int, Field(description='The number of interval units per budget period.', examples=[1])]
    interval_unit: Annotated[str, Field(description='The unit for budget period intervals. One of: day, week, month, year.', examples=['month'])]
