# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated, Any
from pydantic import BaseModel, Field
from collections.abc import Mapping


class Price(BaseModel):
    """
    Price model
    """
    id: str
    unit: Annotated[str, Field(description='The unit in which the amount is billed.', examples=['hour'])]
    region: Annotated[str, Field(description='The region the price is specific to.', examples=['us-east-1'])]
    rate_type: Annotated[str, Field(description='The part of the product the price applies to. (compute, transfer, etc..)', examples=['compute'])]
    currency: Annotated[str, Field(description='The currency of the amount.', examples=['USD'])]
    amount: Annotated[float, Field(description='The amount of money this specific product price costs.', examples=[1.324])]
    details: Annotated[Mapping[str, Any], Field(description='Service specific metadata.', examples=[{'platform': 'linux-enterprise', 'lifecycle': 'on-demand'}])]
