# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict


class ProductsGetParametersQuery(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    provider_id: str | None = None
    service_id: str | None = None
    name: str | None = None
    page: int | None = None
    limit: int | None = None
