# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from pydantic import BaseModel


class ProductsGetParametersQuery(BaseModel):
    provider_id: str | None = None
    service_id: str | None = None
    name: str | None = None
    page: int | None = None
    limit: int | None = None
