# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated, Any
from pydantic import BaseModel, Field
from collections.abc import Mapping


class Product(BaseModel):
    """
    Product model
    """
    id: str
    category: Annotated[str, Field(description='The category of the cloud product', examples=['compute'])]
    name: Annotated[str, Field(description='The common name of the product.', examples=['EC2'])]
    service_id: Annotated[str, Field(description='A unique slug for the service the product belongs to.', examples=['aws-ec2'])]
    provider_id: Annotated[str, Field(description='A unique slug for the provider the product belongs to.', examples=['aws'])]
    details: Annotated[Mapping[str, Any], Field(description='An object of metadata about the product.', examples=[{'gpu': 0, 'name': 'M5 General Purpose 16xlarge', 'vcpu': 64, 'memory': 256, 'clock_speed_ghz': 3.1, 'physical_processor_description': 'Intel Xeon Platinum 8175 (Skylake)', 'network_performance_description': '20 Gigabit'}])]
