# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence
from . import recommendation_action


class ProviderResource(BaseModel):
    """
    ProviderResource model
    """
    token: str
    resource_id: Annotated[str, Field(description='The unique identifier of the Active Resource.', examples=['i-0a1b2c3d4e5f6g7h8'])]
    recommendation_actions: Annotated[Sequence[recommendation_action.RecommendationAction] | None, Field(description='The actions to take to implement the Recommendation.')] = None
