# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class RecommendationAction(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    action: str
    description: str
    potential_savings: Annotated[str, Field(description='Potential savings in dollars', examples=['100.00'])]
    instance_type: str | None = None
    containers: str | None = None
    remediation_cli_command: Annotated[str | None, Field(description='CLI command to remediate this recommendation', examples=['aws ec2 stop-instances --instance-ids i-1234567890abcdef0'])] = None
