# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel, ConfigDict
from . import links as links_1, recommendation_view


class RecommendationViews(BaseModel):
    """
    RecommendationViews model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    links: links_1.Links | None = None
    recommendation_views: Sequence[recommendation_view.RecommendationView] | None = None
