# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class Recommendation(BaseModel):
    """
    Recommendation model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: str
    type: Annotated[str, Field(description='The type of the Recommendation. This is analogous to category, but with a uniform format.', examples=['aws:ec2:co-rightsizing'])]
    category: Annotated[str, Field(description='The category of the Recommendation.', examples=['ec2_compute_optimizer_recommender'])]
    workspace_token: Annotated[str, Field(description='The token for the Workspace the Recommendation is a part of.')]
    provider: Annotated[str, Field(description='The provider the Recommendation is for.')]
    provider_account_id: Annotated[str | None, Field(description='The account ID of the provider. For Azure, this is the subscription ID.')]
    description: str
    potential_savings: Annotated[str | None, Field(description="The monthly potential savings of the Recommendation, converted to the organization's selected currency.", examples=['100.00'])]
    service: Annotated[str, Field(description='The service the Recommendation is for.', examples=['Amazon EC2'])]
    created_at: Annotated[str, Field(description='The date and time, in UTC, the Recommendation was created. ISO 8601 Formatted.')]
    resources_affected_count: Annotated[int, Field(description='The number of ProviderResources related to the Recommendation. Use the `recommendations/:token/resources` endpoint to get the full list of resources.')]
    currency_code: Annotated[str | None, Field(description='The currency code used by the Workspace to which this Recommendation belongs.', examples=['EUR'])] = None
    currency_symbol: Annotated[str | None, Field(description='The currency symbol used by the Workspace to which this Recommendation belongs.', examples=['EUR'])] = None
