# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel, ConfigDict
from . import recommendations_by_type_type_resources_get_parameters_query_provider_id, recommendations_by_type_type_resources_get_parameters_query_status


class RecommendationsByTypeTypeResourcesGetParametersQuery(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    provider_ids: Sequence[recommendations_by_type_type_resources_get_parameters_query_provider_id.RecommendationsByTypeTypeResourcesGetParametersQueryProviderId] | None = None
    billing_account_ids: Sequence[str] | None = None
    account_ids: Sequence[str] | None = None
    regions: Sequence[str] | None = None
    tag_key: str | None = None
    tag_value: str | None = None
    start_date: str | None = None
    end_date: str | None = None
    status: recommendations_by_type_type_resources_get_parameters_query_status.RecommendationsByTypeTypeResourcesGetParametersQueryStatus | None = None
    page: int | None = None
    limit: int | None = None
    workspace_token: str
