# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import Enum


class RecommendationsGetParametersQueryProvider(str, Enum):
    aws = 'aws'
    gcp = 'gcp'
    azure = 'azure'
    kubernetes = 'kubernetes'
    datadog = 'datadog'
