# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel
from . import links as links_1, recommendation_view


class RecommendationViews(BaseModel):
    """
    RecommendationViews model
    """
    links: links_1.Links | None = None
    recommendation_views: Sequence[recommendation_view.RecommendationView] | None = None
