# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel, ConfigDict
from . import recommendations_get_parameters_query_provider, recommendations_get_parameters_query_provider_id, recommendations_get_parameters_query_status


class RecommendationsGetParametersQuery(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    provider_ids: Sequence[recommendations_get_parameters_query_provider_id.RecommendationsGetParametersQueryProviderId] | None = None
    billing_account_ids: Sequence[str] | None = None
    account_ids: Sequence[str] | None = None
    regions: Sequence[str] | None = None
    tag_key: str | None = None
    tag_value: str | None = None
    start_date: str | None = None
    end_date: str | None = None
    status: recommendations_get_parameters_query_status.RecommendationsGetParametersQueryStatus | None = None
    page: int | None = None
    limit: int | None = None
    workspace_token: str | None = None
    provider_account_id: str | None = None
    category: str | None = None
    type: str | None = None
    provider: recommendations_get_parameters_query_provider.RecommendationsGetParametersQueryProvider | None = None
