# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence


class RecommendationView(BaseModel):
    """
    RecommendationView model
    """
    token: str | None = None
    title: Annotated[str | None, Field(description='The title of the RecommendationView.', examples=['Production Recommendations'])] = None
    workspace_token: Annotated[str | None, Field(description='The token for the Workspace the RecommendationView is a part of.')] = None
    start_date: Annotated[str | None, Field(description='Filter recommendations created on/after this YYYY-MM-DD date.', examples=['2024-01-01'])] = None
    end_date: Annotated[str | None, Field(description='Filter recommendations created on/before this YYYY-MM-DD date.', examples=['2024-12-31'])] = None
    provider_ids: Annotated[Sequence[str] | None, Field(description='Filter by one or more providers.')] = None
    billing_account_ids: Annotated[Sequence[str] | None, Field(description='Filter by billing account identifiers.')] = None
    account_ids: Annotated[Sequence[str] | None, Field(description='Filter by cloud account identifiers.')] = None
    regions: Annotated[Sequence[str] | None, Field(description='Filter by region slugs (e.g. us-east-1, eastus, asia-east1).')] = None
    tag_key: Annotated[str | None, Field(description='Filter by tag key (must be used with tag_value).', examples=['environment'])] = None
    tag_value: Annotated[str | None, Field(description='Filter by tag value (requires tag_key).', examples=['production'])] = None
    created_at: Annotated[str | None, Field(description='The date and time, in UTC, the view was created. ISO 8601 Formatted.', examples=['2023-08-04T00:00:00Z'])] = None
    created_by: Annotated[str | None, Field(description='The token for the Creator of this RecommendationView.')] = None
