# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel, ConfigDict
from . import links as links_1, report_notification


class ReportNotifications(BaseModel):
    """
    ReportNotifications model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    links: links_1.Links | None = None
    report_notifications: Sequence[report_notification.ReportNotification]
