# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence
from . import report_notification_change, report_notification_frequency


class ReportNotification(BaseModel):
    """
    ReportNotification model
    """
    token: str
    title: Annotated[str, Field(description='The title of the ReportNotification.', examples=['Acme Report Notification'])]
    cost_report_token: Annotated[str, Field(description='The token for a CostReport the ReportNotification is applied to.', examples=['rprt_abcd1234'])]
    user_tokens: Annotated[Sequence[str], Field(description='The Users that receive the notification.')]
    recipient_channels: Annotated[Sequence[str], Field(description='The Slack or Microsoft Teams channels that receive the notification.')]
    frequency: Annotated[report_notification_frequency.ReportNotificationFrequency, Field(description='The frequency the ReportNotification is sent.', examples=['weekly'])]
    change: Annotated[report_notification_change.ReportNotificationChange, Field(description='The type of change the ReportNotification is tracking.', examples=['percentage'])]
