# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field

from . import change as change_1
from . import frequency as frequency_1


class ReportNotification(BaseModel):
    """
    ReportNotification model
    """

    token: str
    title: Annotated[
        str,
        Field(
            description='The title of the ReportNotification.',
            examples=['Acme Report Notification'],
        ),
    ]
    cost_report_token: Annotated[
        str,
        Field(
            description='The token for a CostReport the ReportNotification is applied to.',
            examples=['rprt_abcd1234'],
        ),
    ]
    user_tokens: Annotated[
        Sequence[str], Field(description='The Users that receive the notification.')
    ]
    recipient_channels: Annotated[
        Sequence[str],
        Field(
            description='The Slack or Microsoft Teams channels that receive the notification.'
        ),
    ]
    frequency: Annotated[
        frequency_1.Frequency,
        Field(
            description='The frequency the ReportNotification is sent.',
            examples=['weekly'],
        ),
    ]
    change: Annotated[
        change_1.Change,
        Field(
            description='The type of change the ReportNotification is tracking.',
            examples=['percentage'],
        ),
    ]
