# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import Enum


class ReportNotificationChange(str, Enum):
    """
    The type of change the ReportNotification is tracking.
    """
    percentage = 'percentage'
    dollars = 'dollars'
