# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from enum import Enum


class ReportNotificationChange(str, Enum):
    """
    The type of change the ReportNotification is tracking.
    """
    percentage = 'percentage'
    dollars = 'dollars'
