# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class ReportForecast(BaseModel):
    """
    ReportForecast model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: str
    title: str
    cost_report_token: str
    scenario_model_tokens: Sequence[str]
    business_metric_token: Annotated[str | None, Field(...)]
    is_default: bool
    created_by_token: Annotated[str | None, Field(...)]
    created_at: str
    updated_at: str
