# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from pydantic import BaseModel


class ResourceReportsGetParametersQuery(BaseModel):
    page: int | None = None
    limit: int | None = None
