# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import BaseModel


class ResourcesGetParametersQuery(BaseModel):
    resource_report_token: str | None = None
    filter: str | None = None
    workspace_token: str | None = None
    include_cost: bool | None = None
    page: int | None = None
    limit: int | None = None
