# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from collections.abc import Sequence


class ResourceReport(BaseModel):
    """
    ResourceReport model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: str
    title: Annotated[str, Field(description='The title of the ResourceReport.', examples=['Acme123 Active Resources'])]
    filter: Annotated[str | None, Field(description='The filter applied to the ResourceReport. Additional documentation available at https://docs.vantage.sh/vql.')]
    created_at: Annotated[str, Field(description='The date and time, in UTC, the report was created. ISO 8601 Formatted.', examples=['2024-03-19T00:00:00Z'])]
    workspace_token: Annotated[str, Field(description='The token for the Workspace the ResourceReport is a part of.')]
    user_token: Annotated[str | None, Field(description='The token for the User who created this ResourceReport.')]
    created_by_token: Annotated[str | None, Field(description='The token for the User or Team who created this ResourceReport.')]
    columns: Annotated[Sequence[str], Field(description='Array of column names configured for the ResourceReport table display.')]
