# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from collections.abc import Sequence
from typing import Annotated
from pydantic import BaseModel, Field


class ResourceReportColumns(BaseModel):
    """
    ResourceReportColumns model
    """
    columns: Annotated[Sequence[str], Field(description='Array of available column names for the specified resource type.')]
