# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class ResourceCost(BaseModel):
    category: Annotated[str, Field(description='The category of the cost.')]
    amount: Annotated[float, Field(description='The cost amount.')]
