# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field

from . import resource_cost


class Resource(BaseModel):
    """
    Resource model
    """

    token: str
    uuid: Annotated[
        str,
        Field(
            description='The unique identifier for the resource.',
            examples=['i-0a1b2c3d4e5f6g7h8'],
        ),
    ]
    type: Annotated[
        str, Field(description='The kind of resource.', examples=['aws_instance'])
    ]
    label: Annotated[str | None, Field(...)]
    metadata: Annotated[
        str | None, Field(description='Type-specific attributes of the resource.')
    ]
    account_id: Annotated[
        str | None,
        Field(description='The provider account where the resource is located.'),
    ]
    billing_account_id: Annotated[
        str | None,
        Field(description='The provider billing account this resource is charged to.'),
    ]
    provider: Annotated[
        str, Field(description='The provider of the resource.', examples=['aws'])
    ]
    region: Annotated[
        str | None,
        Field(
            description='The region where the resource is located. Region values are specific to each provider.',
            examples=['us-west-2'],
        ),
    ]
    costs: Annotated[
        Sequence[resource_cost.ResourceCost] | None,
        Field(description='The cost of the resource broken down by category.'),
    ] = None
    created_at: Annotated[
        str,
        Field(
            description='The date and time when Vantage first observed the resource.'
        ),
    ]
