# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from enum import Enum


class Role(str, Enum):
    """
    The role to assign to the user. Defaults to 'editor'.
    """

    owner = 'owner'
    editor = 'editor'
    viewer = 'viewer'
    integration_owner = 'integration_owner'
