# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field


class SavedFilter(BaseModel):
    """
    SavedFilter model
    """

    token: str
    title: Annotated[
        str,
        Field(
            description='The title of the SavedFilter.',
            examples=['Platform Team Reports'],
        ),
    ]
    cost_report_tokens: Annotated[
        Sequence[str],
        Field(
            description='The tokens for any CostReports the SavedFilter is applied to.'
        ),
    ]
    filter: Annotated[
        str | None,
        Field(
            description="The SavedFilter's filter, applied to any relevant CostReports. Additional documentation available at https://docs.vantage.sh/vql.",
            examples=["costs.provider = 'azure'"],
        ),
    ]
    created_at: Annotated[
        str,
        Field(
            description='The date and time, in UTC, the report was created. ISO 8601 Formatted.',
            examples=['2023-08-04T00:00:00Z'],
        ),
    ]
    created_by: Annotated[
        str | None, Field(description='The token for the Creator of this SavedFilter.')
    ]
    workspace_token: Annotated[
        str,
        Field(description='The token for the Workspace the SavedFilter is a part of.'),
    ]
