# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import scenario_model_period_amount_type


class ScenarioModelPeriod(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    start_at: Annotated[str, Field(description='The ISO 8601 start date of the period.', examples=['2026-01-01'])]
    end_at: Annotated[str | None, Field(description='The ISO 8601 end date of the period.', examples=['2026-03-31'])]
    amount: Annotated[str, Field(description='The period amount as a string to preserve decimal precision.', examples=['1250.75'])]
    amount_type: Annotated[scenario_model_period_amount_type.ScenarioModelPeriodAmountType, Field(description='Whether the amount is in dollars or percent.')]
