# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class ScenarioModelPeriodAmountType(StrEnum):
    """
    Whether the amount is in dollars or percent.
    """
    dollar = 'dollar'
    percent = 'percent'
