# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from collections.abc import Sequence
from . import scenario_model_period


class ScenarioModel(BaseModel):
    """
    ScenarioModel model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: str
    title: str
    priority: Annotated[int | None, Field(...)]
    workspace_token: Annotated[str | None, Field(...)]
    provider: Annotated[str | None, Field(...)]
    service: Annotated[str | None, Field(...)]
    periods: Sequence[scenario_model_period.ScenarioModelPeriod]
    created_by_token: Annotated[str | None, Field(...)]
    created_at: str
    updated_at: str
