# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel


class SendInvoice(BaseModel):
    """
    SendInvoice model
    """
    recipients: Sequence[str]
