# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import display_type1


class Settings(BaseModel):
    """
    The settings for the DashboardWidget.
    """

    display_type: display_type1.DisplayType
