# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class Settings(BaseModel):
    """
    Report settings.
    """

    include_credits: Annotated[
        bool, Field(description='Report will include credits.')
    ] = False
    include_refunds: Annotated[
        bool, Field(description='Report will include refunds.')
    ] = False
    include_discounts: Annotated[
        bool, Field(description='Report will include discounts.')
    ] = True
    include_tax: Annotated[bool, Field(description='Report will include tax.')] = True
    amortize: Annotated[bool, Field(description='Report will amortize.')] = True
    unallocated: Annotated[
        bool, Field(description='Report will show unallocated costs.')
    ] = False
    aggregate_by: Annotated[
        str, Field(description='Report will aggregate by cost or usage.')
    ] = 'cost'
    show_previous_period: Annotated[
        bool,
        Field(
            description='Report will show previous period costs or usage comparison.'
        ),
    ] = True
