# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class SnowflakeMetricFields(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    sql_query: Annotated[str, Field(description='The SQL query used to import Snowflake metrics.', examples=['SELECT date, value, label FROM my_metrics_table'])]
