# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from enum import Enum


class Status(str, Enum):
    """
    The status of the Integration. Can be 'connected', 'error', 'pending', 'importing', 'imported', or 'disconnected'.
    """

    connected = 'connected'
    error = 'error'
    pending = 'pending'
    importing = 'importing'
    imported = 'imported'
    disconnected = 'disconnected'
