# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence


class Tag(BaseModel):
    """
    Tag model
    """
    tag_key: Annotated[str, Field(description='The Tag key.', examples=['aws:createdBy'])]
    hidden: Annotated[bool, Field(description='Whether the Tag has been hidden from the Vantage UI.')]
    providers: Annotated[Sequence[str], Field(description='The unique providers that are covered by the Tag key.')]
