# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence


class TagValue(BaseModel):
    tag_value: Annotated[str, Field(description='The TagValue.', examples=['vantage'])]
    providers: Annotated[Sequence[str], Field(description='The unique providers that are covered by the TagValue.')]
