# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel
from . import tags_get_parameters_query_provider, tags_get_parameters_query_sort_direction


class TagsGetParametersQuery(BaseModel):
    providers: Sequence[tags_get_parameters_query_provider.TagsGetParametersQueryProvider] | None = None
    search_query: str | None = None
    sort_direction: tags_get_parameters_query_sort_direction.TagsGetParametersQuerySortDirection | None = None
    page: int = 1
    limit: int = 100
