# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence

from pydantic import BaseModel

from . import provider7, sort_direction1


class TagsKeyValuesGetParametersQuery(BaseModel):
    providers: Sequence[provider7.Provider] | None = None
    sort_direction: sort_direction1.SortDirection = 'asc'
    search_query: str | None = None
    page: int = 1
    limit: int = 100
