# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence

from pydantic import BaseModel

from . import provider6
from . import sort_direction as sort_direction_1


class TagsGetParametersQuery(BaseModel):
    providers: Sequence[provider6.Provider] | None = None
    search_query: str | None = None
    sort_direction: sort_direction_1.SortDirection | None = None
    page: int = 1
    limit: int = 100
