# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel, ConfigDict
from . import tags_key_values_get_parameters_query_provider, tags_key_values_get_parameters_query_sort_direction


class TagsKeyValuesGetParametersQuery(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    providers: Sequence[tags_key_values_get_parameters_query_provider.TagsKeyValuesGetParametersQueryProvider] | None = None
    sort_direction: tags_key_values_get_parameters_query_sort_direction.TagsKeyValuesGetParametersQuerySortDirection = tags_key_values_get_parameters_query_sort_direction.TagsKeyValuesGetParametersQuerySortDirection.asc
    search_query: str | None = None
    page: int = 1
    limit: int = 100
