# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel
from . import links as links_1, tag


class Tags(BaseModel):
    """
    Tags model
    """
    links: links_1.Links | None = None
    tags: Sequence[tag.Tag]
