# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class TeamMember(BaseModel):
    """
    TeamMember model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Annotated[str, Field(description='The name of the team member.', examples=['John Doe'])]
    email: Annotated[str, Field(description='The email address of the team member.', examples=['john@acme.com'])]
    user_token: Annotated[str, Field(description='The token of the team member.', examples=['usr_abcd1234'])]
    role: Annotated[str, Field(description='The role of the team member in the team.', examples=['editor'])]
