# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel
from . import links as links_1, team


class Teams(BaseModel):
    """
    Teams model
    """
    links: links_1.Links | None = None
    teams: Sequence[team.Team]
