# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence


class Team(BaseModel):
    """
    Team model
    """
    token: str
    name: Annotated[str, Field(description='The name of the Team.', examples=['Cost Savers'])]
    description: Annotated[str | None, Field(description='The description of the Team.', examples=['The Team that saves costs'])]
    workspace_tokens: Annotated[Sequence[str], Field(description='The tokens for any Workspaces that the Team belongs to')]
    user_emails: Annotated[Sequence[str], Field(description='The email addresses for Users that belong to the Team')]
    user_tokens: Annotated[Sequence[str], Field(description='The tokens for Users that belong to the Team')]
    default_dashboard_token: Annotated[str | None, Field(description='The token of the default Dashboard for the Team.', examples=['dshbrd_abcd1234'])]
