# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence

from pydantic import BaseModel

from . import links as links_1
from . import team_member


class TeamMembers(BaseModel):
    """
    TeamMembers model
    """

    links: links_1.Links | None = None
    members: Sequence[team_member.TeamMember]
