# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from enum import Enum


class Type(str, Enum):
    """
    The type of the BillingRule. Note: the values are case insensitive.
    """

    exclusion = 'exclusion'
    adjustment = 'adjustment'
    credit = 'credit'
    charge = 'charge'
    custom = 'custom'
