# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class UnitCostsGetParametersQueryDateBin(StrEnum):
    day = 'day'
    week = 'week'
    month = 'month'
    quarter = 'quarter'
    hour = 'hour'
