# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import date_bin9, order1


class UnitCostsGetParametersQuery(BaseModel):
    cost_report_token: str
    start_date: str | None = None
    end_date: str | None = None
    date_bin: date_bin9.DateBin | None = None
    order: order1.Order = 'desc'
    limit: int | None = None
    page: int | None = None
