# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel
from . import links as links_1, unit_cost


class UnitCosts(BaseModel):
    """
    UnitCosts model
    """
    links: links_1.Links | None = None
    unit_costs: Sequence[unit_cost.UnitCost]
