# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from collections.abc import Sequence
from . import update_async_virtual_tag_config_value_cost_metric, update_async_virtual_tag_config_value_date_range, update_async_virtual_tag_config_value_label_transform, update_async_virtual_tag_config_value_percentage


class UpdateAsyncVirtualTagConfigValue(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    filter: Annotated[str, Field(description='The filter query language to apply to the value. Additional documentation available at https://docs.vantage.sh/vql.')]
    name: Annotated[str | None, Field(description='The name of the value.')] = None
    business_metric_token: Annotated[str | None, Field(description='The token of an associated business metric.')] = None
    label_key: Annotated[str | None, Field(description='The business metric label key used for this virtual tag value.')] = None
    label_values: Annotated[Sequence[str] | None, Field(description='Optional business metric label values. An empty array includes every value for the label key.')] = None
    display_name: Annotated[str | None, Field(description='The display name for an allocation value (cost_metric or percentages). Invalid when name is set.')] = None
    label_transforms: Sequence[update_async_virtual_tag_config_value_label_transform.UpdateAsyncVirtualTagConfigValueLabelTransform] | None = None
    cost_metric: update_async_virtual_tag_config_value_cost_metric.UpdateAsyncVirtualTagConfigValueCostMetric | None = None
    percentages: Sequence[update_async_virtual_tag_config_value_percentage.UpdateAsyncVirtualTagConfigValuePercentage] | None = None
    date_ranges: Annotated[Sequence[update_async_virtual_tag_config_value_date_range.UpdateAsyncVirtualTagConfigValueDateRange] | None, Field(description='Date ranges restricting when this value applies. Each range has optional start_date and end_date (inclusive, YYYY-MM-DD).')] = None
