# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class UpdateBudgetPeriodCadenceIntervalUnit(StrEnum):
    """
    The unit for budget period intervals. One of: day, week, month, year.
    """
    day = 'day'
    week = 'week'
    month = 'month'
    year = 'year'
