# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from collections.abc import Sequence
from typing import Annotated
from pydantic import BaseModel, Field
from . import update_billing_profile_invoice_adjustment_attributes_adjustment_item


class UpdateBillingProfileInvoiceAdjustmentAttributes(BaseModel):
    """
    Invoice adjustments (taxes, fees, etc.)
    """
    token: str | None = None
    adjustment_items: Annotated[Sequence[update_billing_profile_invoice_adjustment_attributes_adjustment_item.UpdateBillingProfileInvoiceAdjustmentAttributesAdjustmentItem] | None, Field(description='Array of adjustment items')] = None
