# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from datetime import date
from pydantic import BaseModel, ConfigDict
from . import update_scenario_model_period_amount_type


class UpdateScenarioModelPeriod(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    start_at: date
    end_at: date | None = None
    amount: float
    amount_type: update_scenario_model_period_amount_type.UpdateScenarioModelPeriodAmountType
