# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from . import update_managed_account_business_information_attributes_metadata


class UpdateManagedAccountBusinessInformationAttributes(BaseModel):
    """
    Business information and custom fields (MSP invoicing accounts only)
    """
    id: int | None = None
    token: str | None = None
    metadata: Annotated[update_managed_account_business_information_attributes_metadata.UpdateManagedAccountBusinessInformationAttributesMetadata | None, Field(description='Business metadata including custom fields')] = None
