# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class UpdateBillingProfileBankingInformationAttributesSecureData(BaseModel):
    """
    Encrypted banking details
    """
    account_number: Annotated[str | None, Field(description='Bank account number (US)')] = None
    routing_number: Annotated[str | None, Field(description='Bank routing number (US)')] = None
    iban: Annotated[str | None, Field(description='International Bank Account Number (EU)')] = None
    swift_bic: Annotated[str | None, Field(description='SWIFT/BIC code (EU)')] = None
