# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import update_billing_profile_banking_information_attributes_secure_data


class UpdateBillingProfileBankingInformationAttributes(BaseModel):
    """
    Banking details (MSP accounts only)
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: str | None = None
    bank_name: Annotated[str | None, Field(description='Name of the bank')] = None
    beneficiary_name: Annotated[str | None, Field(description='Name of the account beneficiary')] = None
    tax_id: Annotated[str | None, Field(description='Tax identification number')] = None
    secure_data: Annotated[update_billing_profile_banking_information_attributes_secure_data.UpdateBillingProfileBankingInformationAttributesSecureData | None, Field(description='Encrypted banking details')] = None
