# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import Enum


class UpdateBillingProfileInvoiceAdjustmentAttributesAdjustmentItemAdjustmentType(str, Enum):
    """
    Type of adjustment
    """
    charge = 'charge'
    credit = 'credit'
    discount = 'discount'
