# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from . import update_access_grant_access


class UpdateAccessGrant(BaseModel):
    """
    Update an AccessGrant.
    """
    access: Annotated[update_access_grant_access.UpdateAccessGrantAccess, Field(description='Allowed or denied access to resource.')]
