# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from enum import Enum


class UpdateFinancialCommitmentReportDateBucket(str, Enum):
    """
    The date bucket of the FinancialCommitmentReport.
    """
    hour = 'hour'
    day = 'day'
    week = 'week'
    month = 'month'
    quarter = 'quarter'
