# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class UpdateFinancialCommitmentReportOnDemandCostsScope(StrEnum):
    """
    The scope for the costs. Possible values: discountable, all.
    """
    discountable = 'discountable'
    all = 'all'
