# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from . import update_billing_profile_invoice_adjustment_attributes_adjustment_item_adjustment_type, update_billing_profile_invoice_adjustment_attributes_adjustment_item_calculation_type


class UpdateBillingProfileInvoiceAdjustmentAttributesAdjustmentItem(BaseModel):
    name: Annotated[str, Field(description='Name of the adjustment')]
    adjustment_type: Annotated[update_billing_profile_invoice_adjustment_attributes_adjustment_item_adjustment_type.UpdateBillingProfileInvoiceAdjustmentAttributesAdjustmentItemAdjustmentType, Field(description='Type of adjustment')] = 'charge'
    calculation_type: Annotated[update_billing_profile_invoice_adjustment_attributes_adjustment_item_calculation_type.UpdateBillingProfileInvoiceAdjustmentAttributesAdjustmentItemCalculationType, Field(description='How the adjustment is calculated')]
    amount: Annotated[float, Field(description='Amount or percentage value')]
