# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import Enum


class UpdateDashboardWidgetSettingsDisplayType(str, Enum):
    table = 'table'
    chart = 'chart'
