# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import Enum


class UpdateWorkspaceExchangeRateDate(str, Enum):
    """
    The date to use for currency conversion.
    """
    daily_rate = 'daily_rate'
    end_of_billing_period_rate = 'end_of_billing_period_rate'
