# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class UpdateManagedAccountBusinessInformationAttributesMetadataCustomField(BaseModel):
    name: Annotated[str | None, Field(description='Custom field name')] = None
    value: Annotated[str | None, Field(description='Custom field value')] = None
