# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from pydantic import BaseModel
from . import update_virtual_tag_config_value_cost_metric_aggregation


class UpdateVirtualTagConfigValueCostMetric(BaseModel):
    filter: str
    aggregation: update_virtual_tag_config_value_cost_metric_aggregation.UpdateVirtualTagConfigValueCostMetricAggregation
