# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from pydantic import BaseModel
from . import update_async_virtual_tag_config_value_cost_metric_aggregation


class UpdateAsyncVirtualTagConfigValueCostMetric(BaseModel):
    filter: str
    aggregation: update_async_virtual_tag_config_value_cost_metric_aggregation.UpdateAsyncVirtualTagConfigValueCostMetricAggregation
