# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import update_access_grant_access


class UpdateAccessGrant(BaseModel):
    """
    Update an AccessGrant.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    access: Annotated[update_access_grant_access.UpdateAccessGrantAccess, Field(description='Allowed or denied access to resource.')]
