# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from pydantic import BaseModel
from . import update_dashboard_widget_settings_display_type


class UpdateDashboardWidgetSettings(BaseModel):
    """
    The settings for the DashboardWidget.
    """
    display_type: update_dashboard_widget_settings_display_type.UpdateDashboardWidgetSettingsDisplayType
