# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import (
    banking_information_attributes1,
    billing_information_attributes1,
    business_information_attributes1,
    invoice_adjustment_attributes1,
)


class UpdateBillingProfile(BaseModel):
    """
    Update a billing profile (MSP invoicing required).
    """

    nickname: Annotated[
        str | None, Field(description='Display name for the billing profile')
    ] = None
    billing_information_attributes: Annotated[
        billing_information_attributes1.BillingInformationAttributes | None,
        Field(description='Billing address and contact information'),
    ] = None
    business_information_attributes: Annotated[
        business_information_attributes1.BusinessInformationAttributes | None,
        Field(description='Business information and custom fields'),
    ] = None
    banking_information_attributes: Annotated[
        banking_information_attributes1.BankingInformationAttributes | None,
        Field(description='Banking details (MSP accounts only)'),
    ] = None
    invoice_adjustment_attributes: Annotated[
        invoice_adjustment_attributes1.InvoiceAdjustmentAttributes | None,
        Field(description='Invoice adjustments (taxes, fees, etc.)'),
    ] = None
