# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class UpdateDashboardDateBin(StrEnum):
    """
    Determines how to group costs in the Dashboard.
    """
    cumulative = 'cumulative'
    day = 'day'
    week = 'week'
    month = 'month'
