# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import update_scenario_model_period


class UpdateScenarioModel(BaseModel):
    """
    Update a ScenarioModel.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    title: str | None = None
    priority: int | None = None
    provider: str | None = None
    service: str | None = None
    workspace_token: str | None = None
    periods: Annotated[Sequence[update_scenario_model_period.UpdateScenarioModelPeriod] | None, Field(description='The periods for the ScenarioModel.')] = None
