# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class UpdateAnomalyAlert(BaseModel):
    """
    Update an AnomalyAlert.
    """

    status: Annotated[str, Field(description='The status of the Anomaly Alert.')]
    feedback: Annotated[
        str | None,
        Field(
            description='Optional additional comments for why this alert is ignored.'
        ),
    ] = None
