# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class UpdateAsyncVirtualTagConfigValueDateRange(BaseModel):
    start_date: Annotated[str | None, Field(description='Inclusive start date (YYYY-MM-DD), or null for unbounded.')] = None
    end_date: Annotated[str | None, Field(description='Inclusive end date (YYYY-MM-DD), or null for unbounded.')] = None
