# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel, ConfigDict


class UpdateReportForecast(BaseModel):
    """
    Update a scenario-model ReportForecast.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    title: str | None = None
    scenario_model_tokens: Sequence[str] | None = None
    business_metric_token: str | None = None
    set_as_default: bool | None = None
