# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from enum import Enum


class UpdateBillingProfileInvoiceAdjustmentAttributesAdjustmentItemAdjustmentType(str, Enum):
    """
    Type of adjustment
    """
    charge = 'charge'
    credit = 'credit'
    discount = 'discount'
