# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence
from . import update_dashboard_date_bin, update_dashboard_date_interval, update_dashboard_widget


class UpdateDashboard(BaseModel):
    """
    Update a Dashboard.
    """
    title: Annotated[str | None, Field(description='The title of the Dashboard.')] = None
    widgets: Annotated[Sequence[update_dashboard_widget.UpdateDashboardWidget] | None, Field(description='The widgets to add to the Dashboard. Currently supports CostReport, ResourceReport, KubernetesEfficiencyReport, and FinancialCommitmentReport.')] = None
    saved_filter_tokens: Annotated[Sequence[str] | None, Field(description='The tokens of the Saved Filters used in the Dashboard.')] = None
    date_bin: Annotated[update_dashboard_date_bin.UpdateDashboardDateBin | None, Field(description='Determines how to group costs in the Dashboard.')] = None
    date_interval: Annotated[update_dashboard_date_interval.UpdateDashboardDateInterval | None, Field(description="Determines the date range in the Dashboard. Incompatible with 'start_date' and 'end_date' parameters.")] = None
    start_date: Annotated[str | None, Field(description="The start date for the date range for costs in the Dashboard. ISO 8601 Formatted. Incompatible with 'date_interval' parameter.")] = None
    end_date: Annotated[str | None, Field(description="The end date for the date range for costs in the Dashboard. ISO 8601 Formatted. Incompatible with 'date_interval' parameter.")] = None
    workspace_token: Annotated[str | None, Field(description='The token of the Workspace the Dashboard belongs to. Required if the API token is associated with multiple Workspaces.')] = None
