# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from collections.abc import Sequence
from typing import Annotated
from pydantic import BaseModel, Field
from . import update_billing_profile_business_information_attributes_metadata_custom_field


class UpdateBillingProfileBusinessInformationAttributesMetadata(BaseModel):
    """
    Business metadata including custom fields
    """
    custom_fields: Annotated[Sequence[update_billing_profile_business_information_attributes_metadata_custom_field.UpdateBillingProfileBusinessInformationAttributesMetadataCustomField] | None, Field(description='Array of custom field objects')] = None
