# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import BaseModel


class UpdateBusinessMetricCloudwatchFieldsDimension(BaseModel):
    name: str | None = None
    value: str | None = None
