# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class UpdateFinancialCommitmentReportGroupings(StrEnum):
    cost_type = 'cost_type'
    commitment_type = 'commitment_type'
    commitment_id = 'commitment_id'
    service = 'service'
    resource_account_id = 'resource_account_id'
    provider_account_id = 'provider_account_id'
    region = 'region'
    cost_category = 'cost_category'
    cost_sub_category = 'cost_sub_category'
    instance_type = 'instance_type'
