# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field

from . import period1


class UpdateBudget(BaseModel):
    """
    Update a Budget.
    """

    name: Annotated[str | None, Field(description='The name of the Budget.')] = None
    cost_report_token: Annotated[
        str | None,
        Field(description='The CostReport token. Ignored for hierarchical Budgets.'),
    ] = None
    child_budget_tokens: Annotated[
        Sequence[str] | None,
        Field(
            description='The tokens of any child Budgets when creating a hierarchical Budget.'
        ),
    ] = None
    periods: Annotated[
        Sequence[period1.Period] | None,
        Field(
            description='The periods for the Budget. The start_at and end_at must be iso8601 formatted e.g. YYYY-MM-DD. Ignored for hierarchical Budgets.'
        ),
    ] = None
