# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import access1


class UpdateAccessGrant(BaseModel):
    """
    Update an AccessGrant.
    """

    access: Annotated[
        access1.Access, Field(description='Allowed or denied access to resource.')
    ]
