# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field

from . import billing_information_attributes2, business_information_attributes2


class UpdateManagedAccount(BaseModel):
    """
    Update a Managed Account.
    """

    name: Annotated[
        str | None, Field(description='The name of the Managed Account.')
    ] = None
    contact_email: Annotated[
        str | None,
        Field(description='The contact email address for the Managed Account.'),
    ] = None
    access_credential_tokens: Annotated[
        Sequence[str] | None,
        Field(
            description='Access Credential (aka Integrations) tokens to assign to the Managed Account.'
        ),
    ] = None
    billing_rule_tokens: Annotated[
        Sequence[str] | None,
        Field(description='Billing Rule tokens to assign to the Managed Account.'),
    ] = None
    email_domain: Annotated[
        str | None,
        Field(
            description='Email domain to associate with this Managed Account for SSO.'
        ),
    ] = None
    msp_billing_profile_token: Annotated[
        str | None,
        Field(
            description='Token of the MSP billing profile to use for this managed account (MSP invoicing accounts only).'
        ),
    ] = None
    billing_information_attributes: Annotated[
        billing_information_attributes2.BillingInformationAttributes | None,
        Field(
            description='Billing address and contact information (MSP invoicing accounts only)'
        ),
    ] = None
    business_information_attributes: Annotated[
        business_information_attributes2.BusinessInformationAttributes | None,
        Field(
            description='Business information and custom fields (MSP invoicing accounts only)'
        ),
    ] = None
