# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class UpdateKubernetesEfficiencyReportDateBucket(StrEnum):
    """
    The date bucket of the KubernetesEfficiencyReport.
    """
    day = 'day'
    week = 'week'
    month = 'month'
    quarter = 'quarter'
