# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import Enum


class UpdateTeamRole(str, Enum):
    """
    The role to assign to the provided Users. Defaults to 'editor' which has editor permissions.
    """
    owner = 'owner'
    editor = 'editor'
    viewer = 'viewer'
