# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class UpdateTag(BaseModel):
    """
    Updates an existing Tag.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    tag_key: str | None = None
    tag_keys: Sequence[str] | None = None
    hidden: Annotated[bool, Field(description='Whether the Tag is hidden from the Vantage UI.')]
