# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from . import update_billing_profile_business_information_attributes_metadata


class UpdateBillingProfileBusinessInformationAttributes(BaseModel):
    """
    Business information and custom fields
    """
    token: str | None = None
    metadata: Annotated[update_billing_profile_business_information_attributes_metadata.UpdateBillingProfileBusinessInformationAttributesMetadata | None, Field(description='Business metadata including custom fields')] = None
