# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class UpdateCostReportDateBin(StrEnum):
    """
    The date bin of the CostReport.
    """
    cumulative = 'cumulative'
    day = 'day'
    week = 'week'
    month = 'month'
    quarter = 'quarter'
    hour = 'hour'
