# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from datetime import date
from collections.abc import Sequence
from . import update_kubernetes_efficiency_report_aggregated_by, update_kubernetes_efficiency_report_date_bucket, update_kubernetes_efficiency_report_date_interval


class UpdateKubernetesEfficiencyReport(BaseModel):
    """
    Update a KubernetesEfficiencyReport.
    """
    title: Annotated[str | None, Field(description='The title of the KubernetesEfficiencyReport.')] = None
    filter: Annotated[str | None, Field(description='The filter query language to apply to the KubernetesEfficiencyReport. Additional documentation available at https://docs.vantage.sh/vql.')] = None
    start_date: Annotated[date | None, Field(description="The start date of the KubernetesEfficiencyReport. ISO 8601 Formatted. Incompatible with 'date_interval' parameter.")] = None
    end_date: Annotated[date | None, Field(description="The end date of the KubernetesEfficiencyReport. ISO 8601 Formatted. Incompatible with 'date_interval' parameter.")] = None
    date_interval: Annotated[update_kubernetes_efficiency_report_date_interval.UpdateKubernetesEfficiencyReportDateInterval | None, Field(description="The date interval of the KubernetesEfficiencyReport. Incompatible with 'start_date' and 'end_date' parameters. Defaults to 'this_month' if start_date and end_date are not provided.")] = None
    aggregated_by: Annotated[update_kubernetes_efficiency_report_aggregated_by.UpdateKubernetesEfficiencyReportAggregatedBy | None, Field(description='The column by which the costs are aggregated.')] = None
    date_bucket: Annotated[update_kubernetes_efficiency_report_date_bucket.UpdateKubernetesEfficiencyReportDateBucket | None, Field(description='The date bucket of the KubernetesEfficiencyReport.')] = None
    groupings: Annotated[Sequence[str] | None, Field(description='Grouping values for aggregating costs on the KubernetesEfficiencyReport. Valid groupings: cluster_id, namespace, labeled, category, pod, label, label:<label_name>.')] = None
