# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field

from . import (
    cloudwatch_fields2,
    cost_report_tokens_with_metadatum1,
    datadog_metric_fields2,
    forecasted_value1,
    value1,
)


class UpdateBusinessMetric(BaseModel):
    """
    Updates an existing BusinessMetric.
    """

    title: Annotated[
        str | None, Field(description='The title of the BusinessMetric.')
    ] = None
    cost_report_tokens_with_metadata: Annotated[
        Sequence[cost_report_tokens_with_metadatum1.CostReportTokensWithMetadatum]
        | None,
        Field(
            description='The tokens for any CostReports that use the BusinessMetric, and the unit scale.'
        ),
    ] = None
    values: Annotated[
        Sequence[value1.Value] | None,
        Field(
            description='The dates, amounts, and (optional) labels for the BusinessMetric.'
        ),
    ] = None
    forecasted_values: Annotated[
        Sequence[forecasted_value1.ForecastedValue] | None,
        Field(
            description='The dates, amounts, and (optional) labels for forecasted BusinessMetric values.'
        ),
    ] = None
    datadog_metric_fields: Annotated[
        datadog_metric_fields2.DatadogMetricFields | None,
        Field(description='Datadog metric configuration fields'),
    ] = None
    cloudwatch_fields: Annotated[
        cloudwatch_fields2.CloudwatchFields | None,
        Field(description='Cloudwatch configuration fields.'),
    ] = None
