# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict
from . import update_virtual_tag_config_value1_label_transform_type


class UpdateVirtualTagConfigValue1LabelTransform(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: update_virtual_tag_config_value1_label_transform_type.UpdateVirtualTagConfigValue1LabelTransformType
    delimiter: str | None = None
    index: int | None = None
    template: str | None = None
