# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from collections.abc import Sequence
from typing import Annotated
from pydantic import BaseModel, Field


class UpdateIntegration(BaseModel):
    """
    Update an Integration.
    """
    workspace_tokens: Annotated[Sequence[str] | None, Field(description='The Workspace tokens to associate to the Integration.')] = None
