# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence
from . import update_async_virtual_tag_config_value_cost_metric, update_async_virtual_tag_config_value_percentage


class UpdateAsyncVirtualTagConfigValue(BaseModel):
    filter: Annotated[str, Field(description='The filter query language to apply to the value. Additional documentation available at https://docs.vantage.sh/vql.')]
    name: Annotated[str | None, Field(description='The name of the value.')] = None
    business_metric_token: Annotated[str | None, Field(description='The token of an associated business metric.')] = None
    cost_metric: update_async_virtual_tag_config_value_cost_metric.UpdateAsyncVirtualTagConfigValueCostMetric | None = None
    percentages: Sequence[update_async_virtual_tag_config_value_percentage.UpdateAsyncVirtualTagConfigValuePercentage] | None = None
