# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import update_access_policy_policy_api_version, update_access_policy_policy_policy


class UpdateAccessPolicyPolicy(BaseModel):
    """
    The AccessPolicy definition as a v1 document with vantage.* VQL.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    api_version: Annotated[update_access_policy_policy_api_version.UpdateAccessPolicyPolicyApiVersion, Field(description='The AccessPolicy document version.', examples=['v1'])]
    policy: Annotated[update_access_policy_policy_policy.UpdateAccessPolicyPolicyPolicy, Field(description='The AccessPolicy rules for this version.')]
