# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class UpdateCostReportSettings(BaseModel):
    """
    Report settings.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    include_credits: Annotated[bool | None, Field(description='Report will include credits.')] = None
    include_refunds: Annotated[bool | None, Field(description='Report will include refunds.')] = None
    include_discounts: Annotated[bool | None, Field(description='Report will include discounts.')] = None
    include_tax: Annotated[bool | None, Field(description='Report will include tax.')] = None
    amortize: Annotated[bool | None, Field(description='Report will amortize.')] = None
    unallocated: Annotated[bool | None, Field(description='Report will show unallocated costs.')] = None
    aggregate_by: Annotated[str | None, Field(description='Report will aggregate by cost or usage.')] = None
    show_previous_period: Annotated[bool | None, Field(description='Report will show previous period costs or usage comparison.')] = None
