# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence
from . import update_managed_account_billing_information_attributes, update_managed_account_business_information_attributes


class UpdateManagedAccount(BaseModel):
    """
    Update a Managed Account.
    """
    name: Annotated[str | None, Field(description='The name of the Managed Account.')] = None
    contact_email: Annotated[str | None, Field(description='The contact email address for the Managed Account.')] = None
    access_credential_tokens: Annotated[Sequence[str] | None, Field(description='Access Credential (aka Integrations) tokens to assign to the Managed Account.')] = None
    billing_rule_tokens: Annotated[Sequence[str] | None, Field(description='Billing Rule tokens to assign to the Managed Account.')] = None
    email_domain: Annotated[str | None, Field(description='Email domain to associate with this Managed Account for SSO.')] = None
    msp_billing_profile_token: Annotated[str | None, Field(description='Token of the MSP billing profile to use for this managed account (MSP invoicing accounts only).')] = None
    billing_information_attributes: Annotated[update_managed_account_billing_information_attributes.UpdateManagedAccountBillingInformationAttributes | None, Field(description='Billing address and contact information (MSP invoicing accounts only)')] = None
    business_information_attributes: Annotated[update_managed_account_business_information_attributes.UpdateManagedAccountBusinessInformationAttributes | None, Field(description='Business information and custom fields (MSP invoicing accounts only)')] = None
