# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class UpdateDashboardWidget1WidgetableType(StrEnum):
    """
    The widget type. Use free_text for a free text widget.
    """
    free_text = 'free_text'
