# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class UpdateKubernetesEfficiencyReportAggregatedBy(StrEnum):
    """
    The column by which the costs are aggregated.
    """
    idle_cost = 'idle_cost'
    amount = 'amount'
    cost_efficiency = 'cost_efficiency'
