# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence


class UpdateManagedAccountBillingInformationAttributes(BaseModel):
    """
    Billing address and contact information (MSP invoicing accounts only)
    """
    id: int | None = None
    token: str | None = None
    company_name: Annotated[str | None, Field(description='Company name for billing')] = None
    country_code: Annotated[str | None, Field(description='ISO country code')] = None
    address_line_1: Annotated[str | None, Field(description='First line of billing address')] = None
    address_line_2: Annotated[str | None, Field(description='Second line of billing address')] = None
    city: Annotated[str | None, Field(description='City for billing address')] = None
    state: Annotated[str | None, Field(description='State or province for billing address')] = None
    postal_code: Annotated[str | None, Field(description='Postal or ZIP code')] = None
    billing_email: Annotated[Sequence[str] | None, Field(description='Array of billing email addresses')] = None
