# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from . import update_segment_report_settings


class UpdateSegment(BaseModel):
    """
    Update a Segment.
    """
    title: Annotated[str | None, Field(description='The title of the Segment.')] = None
    description: Annotated[str | None, Field(description='The description of the Segment.')] = None
    priority: Annotated[int | None, Field(description='The priority of the Segment.')] = None
    track_unallocated: Annotated[bool, Field(description='Track Unallocated Costs which are not assigned to any of the created Segments.')] = False
    report_settings: Annotated[update_segment_report_settings.UpdateSegmentReportSettings | None, Field(description='Report settings configurable on top-level Segments.')] = None
    filter: Annotated[str | None, Field(description='The filter query language to apply to the Segment. Additional documentation available at https://docs.vantage.sh/vql.')] = None
    parent_segment_token: Annotated[str | None, Field(description='The token of the parent Segment this new Segment belongs to. Determines the Workspace the segment is assigned to.')] = None
