# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class UpdateDashboardWidget1ContentType(StrEnum):
    """
    The TipTap document root type.
    """
    doc = 'doc'
