# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated, Any
from pydantic import BaseModel, ConfigDict, Field
from collections.abc import Mapping, Sequence
from . import update_dashboard_widget1_content_type


class UpdateDashboardWidget1Content(BaseModel):
    """
    The required rich-text document for a free text widget.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Annotated[update_dashboard_widget1_content_type.UpdateDashboardWidget1ContentType, Field(description='The TipTap document root type.')]
    content: Sequence[Mapping[str, Any]] | None = None
