# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class UpdateSavedFilter(BaseModel):
    """
    Update a SavedFilter for CostReports.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    title: Annotated[str | None, Field(description='The title of the SavedFilter.')] = None
    filter: Annotated[str | None, Field(description='The filter query language to apply to the SavedFilter, which subsequently gets applied to a CostReport. Additional documentation available at https://docs.vantage.sh/vql.')] = None
