# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class UpdateBillingProfileBusinessInformationAttributesMetadataCustomField(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Annotated[str | None, Field(description='Custom field name')] = None
    value: Annotated[str | None, Field(description='Custom field value')] = None
