# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from enum import Enum


class UpdateNetworkFlowReportDateInterval(str, Enum):
    """
    The date interval of the NetworkFlowReport. Unless 'custom' is used, this is incompatible with 'start_date' and 'end_date' parameters. Defaults to 'last_7_days'.
    """
    last_3_days = 'last_3_days'
    last_7_days = 'last_7_days'
    custom = 'custom'
