# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import Enum


class UpdateAccessGrantAccess(str, Enum):
    """
    Allowed or denied access to resource.
    """
    denied = 'denied'
    allowed = 'allowed'
