# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import update_cost_report_default_forecast_kind


class UpdateCostReportDefaultForecast(BaseModel):
    """
    The default forecast selection for the CostReport.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    kind: Annotated[update_cost_report_default_forecast_kind.UpdateCostReportDefaultForecastKind, Field(description='The default forecast selection kind.')]
    report_forecast_token: Annotated[str | None, Field(description='The token for the report forecast to set as default when kind is report_forecast.')] = None
