# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from . import update_billing_profile_banking_information_attributes, update_billing_profile_billing_information_attributes, update_billing_profile_business_information_attributes, update_billing_profile_invoice_adjustment_attributes


class UpdateBillingProfile(BaseModel):
    """
    Update a billing profile (MSP invoicing required).
    """
    nickname: Annotated[str | None, Field(description='Display name for the billing profile')] = None
    billing_information_attributes: Annotated[update_billing_profile_billing_information_attributes.UpdateBillingProfileBillingInformationAttributes | None, Field(description='Billing address and contact information')] = None
    business_information_attributes: Annotated[update_billing_profile_business_information_attributes.UpdateBillingProfileBusinessInformationAttributes | None, Field(description='Business information and custom fields')] = None
    banking_information_attributes: Annotated[update_billing_profile_banking_information_attributes.UpdateBillingProfileBankingInformationAttributes | None, Field(description='Banking details (MSP accounts only)')] = None
    invoice_adjustment_attributes: Annotated[update_billing_profile_invoice_adjustment_attributes.UpdateBillingProfileInvoiceAdjustmentAttributes | None, Field(description='Invoice adjustments (taxes, fees, etc.)')] = None
