# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class UpdateCostReportDefaultForecastKind(StrEnum):
    """
    The default forecast selection kind.
    """
    baseline = 'baseline'
    report_forecast = 'report_forecast'
