# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict
from . import update_virtual_tag_config_value1_cost_metric_aggregation


class UpdateVirtualTagConfigValue1CostMetric(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    filter: str
    aggregation: update_virtual_tag_config_value1_cost_metric_aggregation.UpdateVirtualTagConfigValue1CostMetricAggregation
