# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field


class UpdateTag(BaseModel):
    """
    Updates an existing Tag.
    """

    tag_key: str | None = None
    tag_keys: Sequence[str] | None = None
    hidden: Annotated[
        bool, Field(description='Whether the Tag is hidden from the Vantage UI.')
    ]
