# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from enum import Enum


class UpdateNetworkFlowReportFlowDirection(str, Enum):
    """
    The flow direction of the NetworkFlowReport.
    """
    ingress = 'ingress'
    egress = 'egress'
