# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence
from . import update_cost_report_business_metric_tokens_with_metadatum_unit_scale


class UpdateCostReportBusinessMetricTokensWithMetadatum(BaseModel):
    business_metric_token: Annotated[str, Field(description='The token of the BusinessMetric to attach to the CostReport.')]
    unit_scale: Annotated[update_cost_report_business_metric_tokens_with_metadatum_unit_scale.UpdateCostReportBusinessMetricTokensWithMetadatumUnitScale, Field(description="Determines the scale of the BusinessMetric's values within the CostReport.")] = 'per_unit'
    label_filter: Annotated[Sequence[str] | None, Field(description='Include only values with these labels in the CostReport.')] = None
