# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import AwareDatetime, BaseModel


class UpdateBusinessMetricForecastedValue(BaseModel):
    date: AwareDatetime
    amount: float
    label: str | None = None
