# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from datetime import date as date_aliased
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import update_budget_period_cadence_interval_unit


class UpdateBudgetPeriodCadence(BaseModel):
    """
    The interval cadence for budget periods. Changing cadence after creation is rejected.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    starts_at: Annotated[date_aliased | None, Field(description='The anchor date for budget period intervals. Send null to clear.')]
    interval_count: Annotated[int | None, Field(description='The number of interval units per budget period.')] = None
    interval_unit: Annotated[update_budget_period_cadence_interval_unit.UpdateBudgetPeriodCadenceIntervalUnit | None, Field(description='The unit for budget period intervals. One of: day, week, month, year.')] = None
