# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from collections.abc import Sequence
from . import update_dashboard_notification_frequency


class UpdateDashboardNotification(BaseModel):
    """
    Update a DashboardNotification.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    title: Annotated[str | None, Field(description='The title of the DashboardNotification.')] = None
    dashboard_token: Annotated[str | None, Field(description='The Dashboard token. Retargeting requires edit access to the new Dashboard.')] = None
    user_tokens: Annotated[Sequence[str] | None, Field(description='The Users that receive the notification.')] = None
    recipient_emails: Annotated[Sequence[str] | None, Field(description="Email addresses that receive the notification. Must be organization users, on the account's SSO domain, or an approved third-party service address.")] = None
    frequency: Annotated[update_dashboard_notification_frequency.UpdateDashboardNotificationFrequency | None, Field(description='The frequency the DashboardNotification is sent. Possible values: daily, weekly, monthly.')] = None
