# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class UpdateUser(BaseModel):
    """
    Update a specific User.
    """
    default_dashboard_token: Annotated[str | None, Field(description='The token of a Dashboard to set as the User default. Send null to clear.')] = None
