# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from datetime import date
from collections.abc import Sequence
from . import update_virtual_tag_config_collapsed_tag_key, update_virtual_tag_config_value


class UpdateVirtualTagConfig(BaseModel):
    """
    Updates an existing VirtualTagConfig.
    """
    key: Annotated[str | None, Field(description='The key of the VirtualTagConfig.')] = None
    overridable: Annotated[bool | None, Field(description='Whether the VirtualTagConfig can override a provider-supplied tag on a matching Cost.')] = None
    backfill_until: Annotated[date | None, Field(description='The earliest month the VirtualTagConfig should be backfilled to.')] = None
    collapsed_tag_keys: Annotated[Sequence[update_virtual_tag_config_collapsed_tag_key.UpdateVirtualTagConfigCollapsedTagKey] | None, Field(description='Tag keys to collapse values for.')] = None
    values: Annotated[Sequence[update_virtual_tag_config_value.UpdateVirtualTagConfigValue] | None, Field(description='Values for the VirtualTagConfig, with match precedence determined by order in the list.')] = None
