# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class UpdateCostReportSettings(BaseModel):
    """
    Report settings.
    """
    include_credits: Annotated[bool | None, Field(description='Report will include credits.')] = None
    include_refunds: Annotated[bool | None, Field(description='Report will include refunds.')] = None
    include_discounts: Annotated[bool | None, Field(description='Report will include discounts.')] = None
    include_tax: Annotated[bool | None, Field(description='Report will include tax.')] = None
    amortize: Annotated[bool | None, Field(description='Report will amortize.')] = None
    unallocated: Annotated[bool | None, Field(description='Report will show unallocated costs.')] = None
    aggregate_by: Annotated[str | None, Field(description='Report will aggregate by cost or usage.')] = None
    show_previous_period: Annotated[bool | None, Field(description='Report will show previous period costs or usage comparison.')] = None
