# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class UpdateDashboardWidget1SettingsGrid(BaseModel):
    """
    The widget's size and position in the dashboard's 12-column grid.
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    x: Annotated[int, Field(description='The zero-based horizontal position.', ge=0, le=11)]
    y: Annotated[int, Field(description='The zero-based vertical position.')]
    w: Annotated[int, Field(description='The widget width in grid columns.', ge=1, le=12)]
    h: Annotated[int, Field(description='The widget height in grid rows.')]
