# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field


class UpdateBudgetAlert(BaseModel):
    """
    Updates an existing BudgetAlert.
    """

    budget_tokens: Annotated[
        Sequence[str] | None,
        Field(description='The tokens of the Budget that has the alert.'),
    ] = None
    threshold: Annotated[
        int | None,
        Field(
            description='The threshold amount that must be met for the alert to fire.'
        ),
    ] = None
    user_tokens: Annotated[
        Sequence[str] | None,
        Field(description='The tokens of the users that receive the alert.'),
    ] = None
    duration_in_days: Annotated[
        str | None,
        Field(
            description='The number of days from the start or end of the month to trigger the alert if the threshold is reached. For the full month, pass an empty value.'
        ),
    ] = None
    period_to_track: Annotated[
        str | None,
        Field(
            description='The period tracked on the alert. Used with duration_in_days to determine the time window of the alert. Defaults to start_of_the_month if not passed. Possible values: start_of_the_month, end_of_the_month.'
        ),
    ] = None
    recipient_channels: Annotated[
        Sequence[str] | None,
        Field(
            description='The channels receiving the alerts. Requires an integration provider to be connected.'
        ),
    ] = None
