# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from enum import StrEnum


class UpdateDashboardWidget1SettingsKpiCalculation(StrEnum):
    """
    The aggregation used when display_type is kpi.
    """
    sum = 'sum'
    average = 'average'
