# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-12T16:38:06+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class UsagePartial(BaseModel):
    amount: Annotated[str, Field(description='The sum of the usage.', examples=['4.25'])]
    unit: Annotated[str, Field(description='The unit of the usage.', examples=['USD'])]
