# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class UsagePartial(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    amount: Annotated[str, Field(description='The sum of the usage.', examples=['4.25'])]
    unit: Annotated[str, Field(description='The unit of the usage.', examples=['USD'])]
