# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class UserFeedback(BaseModel):
    """
    UserFeedback model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: Annotated[str, Field(description='Token of the feedback')]
    message: Annotated[str, Field(description='User feedback message')]
    created_by_token: Annotated[str | None, Field(description='Token of the creator of the feedback')] = None
    created_at: Annotated[str, Field(description='Feedback creation timestamp', examples=['2023-01-01T00:00:00Z'])]
