# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class UserFeedback(BaseModel):
    """
    UserFeedback model
    """

    token: Annotated[str, Field(description='Token of the feedback')]
    message: Annotated[str, Field(description='User feedback message')]
    created_by_token: Annotated[
        str | None, Field(description='Token of the creator of the feedback')
    ] = None
    created_at: Annotated[
        str,
        Field(
            description='Feedback creation timestamp', examples=['2023-01-01T00:00:00Z']
        ),
    ]
