# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class User(BaseModel):
    """
    User model
    """
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: str
    name: Annotated[str | None, Field(description='The name of the User.', examples=['John Doe'])]
    email: Annotated[str, Field(description='The email of the User.', examples=['john_doe@acme.com'])]
    role: Annotated[str, Field(description='The role of the User.', examples=['Admin'])]
    default_dashboard_token: Annotated[str | None, Field(description='The token of the default Dashboard for the User.', examples=['dshbrd_abcdef123456'])] = None
    last_seen_at: Annotated[str | None, Field(description='The last time the User logged in.', examples=['2024-01-01T00:00:00Z'])] = None
