# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel
from . import links as links_1, user_costs_upload


class UserCostsUploads(BaseModel):
    """
    UserCostsUploads model
    """
    links: links_1.Links | None = None
    user_costs_uploads: Sequence[user_costs_upload.UserCostsUpload]
