# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class UserCostsUpload(BaseModel):
    """
    UserCostsUpload model
    """
    token: Annotated[str, Field(description='The token of the UserCostsUpload.', examples=['usr_csts_upld_1234'])]
    filename: Annotated[str, Field(description='The filename of the uploaded costs UserCostsUpload.', examples=['usr_csts_upld_1234.parquet'])]
    amount: Annotated[str, Field(description='The total amount of the costs in the UserCostsUpload.', examples=['1234.56'])]
    start_date: Annotated[str, Field(description='The start date of the costs in the UserCostsUpload.', examples=['2021-01-01'])]
    end_date: Annotated[str, Field(description='The end date of the costs in the UserCostsUpload.', examples=['2021-01-31'])]
    import_status: Annotated[str, Field(description='Import status of the UserCostsUpload.', examples=['processing'])]
    created_by_token: Annotated[str, Field(description='The token of the Creator of the UserCostsUpload.', examples=['usr_1234'])]
    created_at: Annotated[str, Field(description='When the UserCostsUpload was uploaded.', examples=['2021-01-01T00:00:00Z'])]
