# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class User(BaseModel):
    """
    User model
    """
    token: str
    name: Annotated[str | None, Field(description='The name of the User.', examples=['John Doe'])]
    email: Annotated[str, Field(description='The email of the User.', examples=['john_doe@acme.com'])]
    role: Annotated[str, Field(description='The role of the User.', examples=['Admin'])]
    last_seen_at: Annotated[str | None, Field(description='The last time the User logged in.', examples=['2024-01-01T00:00:00Z'])] = None
