# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from collections.abc import Sequence
from typing import Annotated

from pydantic import BaseModel, Field

from . import cost_metric2, percentage2


class Value(BaseModel):
    filter: Annotated[
        str,
        Field(
            description='The filter query language to apply to the value. Additional documentation available at https://docs.vantage.sh/vql.'
        ),
    ]
    name: Annotated[str | None, Field(description='The name of the value.')] = None
    business_metric_token: Annotated[
        str | None, Field(description='The token of an associated business metric.')
    ] = None
    cost_metric: cost_metric2.CostMetric | None = None
    percentages: Sequence[percentage2.Percentage] | None = None
