# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class VirtualTagConfigValueCostMetricAggregation(BaseModel):
    tag: Annotated[str | None, Field(description='The tag to aggregate on.')] = None
