# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from collections.abc import Sequence
from pydantic import BaseModel
from . import virtual_tag_config


class VirtualTagConfigs(BaseModel):
    """
    VirtualTagConfigs model
    """
    virtual_tag_configs: Sequence[virtual_tag_config.VirtualTagConfig]
