# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class VirtualTagConfigValuePercentage(BaseModel):
    value: Annotated[str, Field(description='The tag value associated with a percentage of matched costs.', examples=['cost-center-a'])]
    pct: Annotated[float, Field(description='The percentage of matched costs associated with the value.', examples=[50.0])]
