# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from . import virtual_tag_config_value_label_transform_type


class VirtualTagConfigValueLabelTransform(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Annotated[virtual_tag_config_value_label_transform_type.VirtualTagConfigValueLabelTransformType, Field(description='The label transform type.')]
    delimiter: Annotated[str | None, Field(description='Delimiter used by split transforms.')] = None
    index: Annotated[int | None, Field(description='Zero-based index used by split transforms.')] = None
    template: Annotated[str | None, Field(description='Template used by format transforms.')] = None
