# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import virtual_tag_config_value_cost_metric_aggregation


class VirtualTagConfigValueCostMetric(BaseModel):
    filter: Annotated[
        str | None, Field(description='The filter VQL for the cost metric.')
    ]
    aggregation: (
        virtual_tag_config_value_cost_metric_aggregation.VirtualTagConfigValueCostMetricAggregation
    )
