# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence
from . import virtual_tag_config_provider_status


class VirtualTagConfigStatus(BaseModel):
    """
    VirtualTagConfigStatus model
    """
    token: Annotated[str, Field(description='The token of the VirtualTagConfig.', examples=['vtag_1234'])]
    processing: Annotated[bool, Field(description='Whether the VirtualTagConfig is currently processing. True if any provider has not completed processing.')]
    providers: Annotated[Sequence[virtual_tag_config_provider_status.VirtualTagConfigProviderStatus], Field(description='Processing status broken down by provider.')]
