# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from collections.abc import Sequence
from . import virtual_tag_config_value_cost_metric, virtual_tag_config_value_date_range, virtual_tag_config_value_percentage


class VirtualTagConfigValue(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    filter: Annotated[str | None, Field(description='The filter VQL for the Value.', examples=["costs.provider = 'aws' AND costs.service = 'Amazon Simple Storage Service'"])]
    name: Annotated[str | None, Field(description='The name of the Value.', examples=['Informatics'])] = None
    business_metric_token: Annotated[str | None, Field(description='The token of the associated BusinessMetric.', examples=['bsnss_mtrc_abc123'])] = None
    cost_metric: virtual_tag_config_value_cost_metric.VirtualTagConfigValueCostMetric | None = None
    percentages: Annotated[Sequence[virtual_tag_config_value_percentage.VirtualTagConfigValuePercentage] | None, Field(description='Labeled percentage allocations for matching costs.')] = None
    date_ranges: Annotated[Sequence[virtual_tag_config_value_date_range.VirtualTagConfigValueDateRange] | None, Field(description='Date ranges restricting when this value applies.')] = None
