# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class VirtualTagConfigValueDateRange(BaseModel):
    start_date: Annotated[str | None, Field(description='The start date of the range (inclusive), or null for unbounded.')]
    end_date: Annotated[str | None, Field(description='The end date of the range (inclusive), or null for unbounded.')]
