# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence
from . import virtual_tag_config_value_cost_metric, virtual_tag_config_value_percentage


class VirtualTagConfigValue(BaseModel):
    filter: Annotated[str | None, Field(description='The filter VQL for the Value.', examples=["costs.provider = 'aws' AND costs.service = 'Amazon Simple Storage Service'"])]
    name: Annotated[str | None, Field(description='The name of the Value.', examples=['Informatics'])] = None
    business_metric_token: Annotated[str | None, Field(description='The token of the associated BusinessMetric.', examples=['bsnss_mtrc_abc123'])] = None
    cost_metric: virtual_tag_config_value_cost_metric.VirtualTagConfigValueCostMetric | None = None
    percentages: Annotated[Sequence[virtual_tag_config_value_percentage.VirtualTagConfigValuePercentage] | None, Field(description='Labeled percentage allocations for matching costs.')] = None
