# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from collections.abc import Sequence


class VirtualTagConfigCollapsedTagKey(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    key: Annotated[str, Field(description='The tag key to collapse values for.', examples=['team'])]
    providers: Annotated[Sequence[str] | None, Field(description='The providers this collapsed tag key applies to. Defaults to all providers when omitted.')] = None
    filter: Annotated[str | None, Field(description='The VQL filter this collapsed tag key applies to.', examples=["(costs.provider = 'aws') OR (costs.provider = 'gcp')"])] = None
