# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from pydantic import BaseModel, ConfigDict


class VirtualTagConfigsGetParametersQuery(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    q: str | None = None
