# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field
from collections.abc import Sequence


class VirtualTagConfigCollapsedTagKey(BaseModel):
    key: Annotated[str, Field(description='The tag key to collapse values for.', examples=['team'])]
    providers: Annotated[Sequence[str], Field(description='The providers this collapsed tag key applies to. Defaults to all providers.')]
