# generated by datamodel-codegen:
#   filename:  openapi_spec.json

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field


class VirtualTagConfigValueCostMetricAggregation(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    tag: Annotated[str | None, Field(description='The tag to aggregate on.')] = None
