# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-06T22:56:33+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import settings3


class Widget(BaseModel):
    widgetable_token: Annotated[
        str, Field(description='The token of the represented Resource.')
    ]
    title: Annotated[
        str | None,
        Field(
            description='The title of the Widget (defaults to the title of the Resource).'
        ),
    ] = None
    settings: Annotated[
        settings3.Settings | None,
        Field(description='The settings for the DashboardWidget.'),
    ] = None
