# generated by datamodel-codegen:
#   filename:  openapi_spec.json
#   timestamp: 2026-02-07T22:31:34+00:00

from __future__ import annotations
from typing import Annotated
from pydantic import BaseModel, Field


class Workspace(BaseModel):
    """
    Workspace model
    """
    token: str
    name: Annotated[str, Field(description='The name of the Workspace.', examples=['Acme Corp.'])]
    created_at: Annotated[str, Field(description='The date and time, in UTC, the Workspace was created. ISO 8601 Formatted.', examples=['2023-08-04T00:00:00Z'])]
    enable_currency_conversion: Annotated[bool, Field(description='Whether or not currency conversion is enabled for the Workspace.')]
    currency: Annotated[str, Field(description='The currency code for the Workspace that will be used for currency conversion.', examples=['USD'])]
    exchange_rate_date: Annotated[str, Field(description='The exchange rate date that will be used to convert currency for your cost data.')]
