"""
Manually maintaining an __all__ list to include both the custom models AND the generated ones would be
difficult and error-prone so we use wildcard imports here. To avoid linter issues, we disable the
relevant checks
"""

# ruff: noqa: I001, F403
# Import everything from gen_models first
from . import gen_models
from .gen_models import *

# Then import custom models to override the generated ones
from .common import (  # type: ignore[assignment]
    AccessGrantTokenParams,
    AnomalyAlertTokenParams,
    AnomalyNotification,
    AnomalyNotifications,
    AnomalyNotificationTokenParams,
    AuditLogTokenParams,
    BillingRuleTokenParams,
    Budget,
    BudgetAlertsBudgetAlertTokenPutRequest,
    BudgetAlertsPostRequest,
    BudgetAlertTokenParams,
    Budgets,
    BudgetTokenParams,
    BusinessMetricTokenParams,
    IntegrationsIntegrationTokenPutRequest,
    WorkspacesWorkspaceTokenPutRequest,
    CostAlertTokenParams,
    CostAlertEventTokenParams,
    CreateCostReport,
    CostReport,
    DashboardTokenParams,
    DataExport,
    DataExportManifest,
    CostReports,
    CostReportTokenParams,
    CostsDataExportsPostRequest,
    UnitCostsDataExportsPostRequest,
    CanvasTokenParams,
    FinancialCommitmentReportTokenParams,
    KubernetesEfficiencyReportTokenParams,
    ManagedAccountTokenParams,
    NetworkFlowReportTokenParams,
    ProductIdParams,
    ProductPriceIdParams,
    RecommendationTokenParams,
    RecommendationResource,
    RecommendationResources,
    RecommendationResourceTokenParams,
    RecommendationTypeParams,
    ReportNotificationTokenParams,
    ResourceReportTokenParams,
    ResourceTokenParams,
    SavedFilterTokenParams,
    SegmentTokenParams,
    TagKeyParams,
    TeamTokenParams,
    UserTokenParams,
    VirtualTagTokenParams,
    FolderTokenParams,
    DataExportTokenParams,
    IntegrationTokenParams,
    WorkspaceTokenParams,
    Recommendation,
    Recommendations,
    CreateVirtualTagConfigValue,
    VirtualTagConfig,
    VirtualTagConfigCollapsedTagKey,
    VirtualTagConfigValue,
    VirtualTagConfigs,
)

__all__ = [
    "AccessGrantTokenParams",
    "AnomalyAlertTokenParams",
    "AnomalyNotification",
    "AnomalyNotificationTokenParams",
    "AnomalyNotifications",
    "AuditLogTokenParams",
    "BillingRuleTokenParams",
    "Budget",
    "BudgetAlertTokenParams",
    "BudgetAlertsBudgetAlertTokenPutRequest",
    "BudgetAlertsPostRequest",
    "BudgetTokenParams",
    "Budgets",
    "BusinessMetricTokenParams",
    "CanvasTokenParams",
    "CostAlertEventTokenParams",
    "CostAlertTokenParams",
    "CostReport",
    "CostReportTokenParams",
    "CostReports",
    "CostsDataExportsPostRequest",
    "CreateCostReport",
    "CreateVirtualTagConfigValue",
    "DashboardTokenParams",
    "DataExport",
    "DataExportManifest",
    "DataExportTokenParams",
    "FinancialCommitmentReportTokenParams",
    "FolderTokenParams",
    "IntegrationTokenParams",
    "IntegrationsIntegrationTokenPutRequest",
    "KubernetesEfficiencyReportTokenParams",
    "ManagedAccountTokenParams",
    "NetworkFlowReportTokenParams",
    "ProductIdParams",
    "ProductPriceIdParams",
    "Recommendation",
    "RecommendationResource",
    "RecommendationResourceTokenParams",
    "RecommendationResources",
    "RecommendationTokenParams",
    "RecommendationTypeParams",
    "Recommendations",
    "ReportNotificationTokenParams",
    "ResourceReportTokenParams",
    "ResourceTokenParams",
    "SavedFilterTokenParams",
    "SegmentTokenParams",
    "TagKeyParams",
    "TeamTokenParams",
    "UnitCostsDataExportsPostRequest",
    "UserTokenParams",
    "VirtualTagConfig",
    "VirtualTagConfigCollapsedTagKey",
    "VirtualTagConfigValue",
    "VirtualTagConfigs",
    "VirtualTagTokenParams",
    "WorkspaceTokenParams",
    "WorkspacesWorkspaceTokenPutRequest",
]

# Re-export the generated models (brought in via the wildcard import above) so that
# downstream consumers' type checkers do not flag them as private re-exports
# (reportPrivateImportUsage). Declaring __all__ above otherwise makes it the
# authoritative public interface, excluding the wildcard-imported names.
__all__ += gen_models.__all__
